#ifndef RCV_CUST_KEYS_H
#define RCV_CUST_KEYS_H

#include <linux/input.h>

#define RECOVERY_KEY_DOWN     KEY_VOLUMEDOWN
#define RECOVERY_KEY_UP       KEY_VOLUMEDOWN
#define RECOVERY_KEY_ENTER    KEY_POWER
#define RECOVERY_KEY_MENU     KEY_VOLUMEUP

#endif /* RCV_CUST_KEYS_H */
