#ifndef FTM_CUST_LED_H
#define FTM_CUST_LED_H

#define CUST_LED_HAVE_BUTTON_BACKLIGHT
#define CUST_HAVE_NLEDS
#define CUST_LED_HAVE_RED
//#define CUST_LED_HAVE_GREEN
#define CUST_LED_HAVE_GREEN
#define CUST_LED_HAVE_BLUE

#endif /* FTM_CUST_LED_H */
