EXTRA_CFLAGS += -D_USB_NORMAL_

obj-y := mu3d_hal.o

mu3d_hal-y := mu3d_hal_osal.o \
              mu3d_hal_qmu_drv.o \
              mu3d_hal_usb_drv.o \
              mu3d_hal_phy.o \
              mu3d_hal_comm.o
