#ifndef ANDROID_AUDIODEF_H
#define ANDROID_AUDIODEF_H

// define this to enalbe pc emualtoe
//#define PC_EMULATION

#define ENABLE_LOG_HARDWARE
#define ENABLE_LOG_STREAMOUT
#define ENABLE_LOG_STREAMIN
#define ENABLE_LOG_VOLUMECONTROLLER
#define ENABLE_LOG_RESOURCEMANAGER
#define ENABLE_LOG_ANA
#define ENABLE_LOG_AFE
#define ENABLE_LOG_AUDIOFLINGER
#define ENABLE_LOG_SPEECHCONTROL

#define ENABLE_LOG_AUDIOPOLICYSERVICE
#define ENABLE_LOG_AUDIOPOLICYANAGER
#define ENABLE_LOG_A2DPINTERFACE
#define ENABLE_LOG_AUDIO_MIXER
#define ENABLE_LOG_I2S
#define ENABLE_LOG_I2SSTREAMIN

// for audio_config_definition
//#define MTK_DUAL_MIC_SUPPORT

#endif