/*
 * (c) MediaTek Inc. 20005
 */

 
#ifndef __GC0312_SENSOR_H
#define __GC0312_SENSOR_H


#define VGA_PERIOD_PIXEL_NUMS						694
#define VGA_PERIOD_LINE_NUMS						488

#define IMAGE_SENSOR_VGA_GRAB_PIXELS			0
#define IMAGE_SENSOR_VGA_GRAB_LINES			1

#define IMAGE_SENSOR_VGA_WIDTH					(640)
#define IMAGE_SENSOR_VGA_HEIGHT					(480)

#define IMAGE_SENSOR_PV_WIDTH					(IMAGE_SENSOR_VGA_WIDTH - 8)
#define IMAGE_SENSOR_PV_HEIGHT					(IMAGE_SENSOR_VGA_HEIGHT - 6)

#define IMAGE_SENSOR_FULL_WIDTH					(IMAGE_SENSOR_VGA_WIDTH - 8)
#define IMAGE_SENSOR_FULL_HEIGHT					(IMAGE_SENSOR_VGA_HEIGHT - 6)

#define GC0312_WRITE_ID							0x42
#define GC0312_READ_ID								0x43


#define GC0312_SENSOR_ID	GC0312_YUV_SENSOR_ID
// GC0312 SENSOR Chip ID: 0xb310

typedef enum
{
	GC0312_RGB_Gamma_m1 = 0,
	GC0312_RGB_Gamma_m2,
	GC0312_RGB_Gamma_m3,
	GC0312_RGB_Gamma_m4,
	GC0312_RGB_Gamma_m5,
	GC0312_RGB_Gamma_m6,
	GC0312_RGB_Gamma_night
}GC0312_GAMMA_TAG;



UINT32 GC0312Open(void);
UINT32 GC0312Control(MSDK_SCENARIO_ID_ENUM ScenarioId, MSDK_SENSOR_EXPOSURE_WINDOW_STRUCT *pImageWindow, MSDK_SENSOR_CONFIG_STRUCT *pSensorConfigData);
UINT32 GC0312FeatureControl(MSDK_SENSOR_FEATURE_ENUM FeatureId, UINT8 *pFeaturePara,UINT32 *pFeatureParaLen);
UINT32 GC0312GetInfo(MSDK_SCENARIO_ID_ENUM ScenarioId, MSDK_SENSOR_INFO_STRUCT *pSensorInfo, MSDK_SENSOR_CONFIG_STRUCT *pSensorConfigData);
UINT32 GC0312GetResolution(MSDK_SENSOR_RESOLUTION_INFO_STRUCT *pSensorResolution);
UINT32 GC0312Close(void);

#endif /* __SENSOR_H */



