#######################################
# Sepcify source files
#######################################
mach_obj += $(MTK_PLATFORM)/mach/arm/sec_lib.o
mach_obj += $(MTK_PLATFORM)/mach/arm/sec_uid.o
mach_obj += $(MTK_PLATFORM)/mach/arm/hacc_lib.o
mach_obj += $(MTK_PLATFORM)/mach/arm/hacc_export.o
mach_obj += $(MTK_PLATFORM)/mach/arm/hacc_hk.o
mach_obj += $(MTK_PLATFORM)/mach/arm/hacc_sk.o

# HEADER FILE
EXTRA_CFLAGS += -I$(src)/asf/asf_inc
