
# Makefile for the power golden setting.
#

obj-y += mt_power_gs.o
obj-y += mt_power_gs_array.o
obj-y += mt_power_gs_suspend.o
obj-y += mt_power_gs_2g_paging.o
obj-y += mt_power_gs_3g_paging.o
obj-y += mt_power_gs_tdd_paging.o
obj-y += mt_power_gs_2g_talking.o
obj-y += mt_power_gs_3g_talking.o
obj-y += mt_power_gs_tdd_talking.o
obj-y += mt_power_gs_data_connection.o
obj-y += mt_power_gs_connsys.o
obj-y += mt_power_gs_dpidle.o
obj-y += mt_power_gs_idle.o
obj-y += mt_power_gs_audio_playback.o
obj-y += mt_power_gs_video_record.o
