#ifndef _MOTIONTRACK_CONFIG_H
#define _MOTIONTRACK_CONFIG_H

#define MOTIONTRACK_DEFAULT_MODE            MFBMM_MODE_LAST_ON_TOP
#define MOTIONTRACK_DEFAULT_MAX_MOVE_RANGE  4
#define MOTIONTRACK_DEFAULT_THREAD_NUM      1

#endif /* _MOTIONTRACK_CONFIG_H */


