ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/dispsys/
ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/smi/
ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/gud/MobiCoreKernelApi/public
ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/gud/MobiCoreKernelApi/include
ccflags-y += -I$(MTK_PATH_SOURCE)/../trustzone/vendor/trustonic/t-base/trustlets


#$(warning hahaha)
#$(warning $(MTK_PATH_PLATFORM))
#$(warning $(MTK_PATH_SOURCE))
#$(warning $(CONFIG_TRUSTONIC_TEE_SUPPORT))
#$(warning $(CONFIG_MTK_SEC_VIDEO_PATH_SUPPORT))

obj-y += m4u.o m4u_kernel.o m4u_priv.o
