HW_INIT_ONLY :=
CFG_BOOT_ARGUMENT :=1
CFG_BATTERY_DETECT :=0
CFG_EMERGENCY_DL_SUPPORT :=0
CFG_RAM_CONSOLE :=0
CFG_UART_TOOL_HANDSHAKE :=1
CFG_USB_TOOL_HANDSHAKE :=0
CFG_USB_DOWNLOAD :=1
CFG_PMT_SUPPORT :=0

CFG_LOAD_MD_ROM :=0
CFG_LOAD_MD_RAMDISK :=0
CFG_LOAD_SLT_MD :=1
CFG_LOAD_AP_ROM :=1
CFG_LOAD_UBOOT :=0

CFG_LOAD_CONN_SYS :=0
CFG_APWDT_DISABLE :=1
