
# Makefile for the power golden setting.
#

obj-y += mt_power_gs.o
obj-y += mt_power_gs_array.o
obj-y += mt_power_gs_suspend.o
obj-y += mt_power_gs_dpidle.o
obj-y += mt_power_gs_idle.o
obj-y += mt_power_gs_audio_playback.o
obj-y += mt_power_gs_video_record.o
