extern void upmu_set_rg_vcdt_hv_en(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_chr_ldo_det(void);
extern void upmu_set_rg_pchr_automode(kal_uint32 val);
extern void upmu_set_rg_csdac_en(kal_uint32 val);
extern void upmu_set_rg_chr_en(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_chrdet(void);
extern kal_uint32 upmu_get_rgs_vcdt_lv_det(void);
extern kal_uint32 upmu_get_rgs_vcdt_hv_det(void);
extern void upmu_set_rg_vcdt_lv_vth(kal_uint32 val);
extern void upmu_set_rg_vcdt_hv_vth(kal_uint32 val);
extern void upmu_set_rg_vbat_cv_en(kal_uint32 val);
extern void upmu_set_rg_vbat_cc_en(kal_uint32 val);
extern void upmu_set_rg_cs_en(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_cs_det(void);
extern kal_uint32 upmu_get_rgs_vbat_cv_det(void);
extern kal_uint32 upmu_get_rgs_vbat_cc_det(void);
extern void upmu_set_rg_vbat_cv_vth(kal_uint32 val);
extern void upmu_set_rg_vbat_cc_vth(kal_uint32 val);
extern void upmu_set_rg_cs_vth(kal_uint32 val);
extern void upmu_set_rg_pchr_tohtc(kal_uint32 val);
extern void upmu_set_rg_pchr_toltc(kal_uint32 val);
extern void upmu_set_rg_vbat_ov_en(kal_uint32 val);
extern void upmu_set_rg_vbat_ov_vth(kal_uint32 val);
extern void upmu_set_rg_vbat_ov_deg(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_vbat_ov_det(void);
extern void upmu_set_rg_baton_en(kal_uint32 val);
extern void upmu_set_rg_baton_ht_en(kal_uint32 val);
extern void upmu_set_baton_tdet_en(kal_uint32 val);
extern void upmu_set_rg_baton_ht_trim(kal_uint32 val);
extern void upmu_set_rg_baton_ht_trim_set(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_baton_undet(void);
extern void upmu_set_rg_csdac_data(kal_uint32 val);
extern void upmu_set_rg_frc_csvth_usbdl(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_pchr_flag_out(void);
extern void upmu_set_rg_pchr_flag_en(kal_uint32 val);
extern void upmu_set_rg_otg_bvalid_en(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_otg_bvalid_det(void);
extern void upmu_set_rg_pchr_flag_sel(kal_uint32 val);
extern void upmu_set_rg_pchr_testmode(kal_uint32 val);
extern void upmu_set_rg_csdac_testmode(kal_uint32 val);
extern void upmu_set_rg_pchr_rst(kal_uint32 val);
extern void upmu_set_rg_pchr_ft_ctrl(kal_uint32 val);
extern void upmu_set_rg_chrwdt_td(kal_uint32 val);
extern void upmu_set_rg_chrwdt_en(kal_uint32 val);
extern void upmu_set_rg_chrwdt_wr(kal_uint32 val);
extern void upmu_set_rg_pchr_rv(kal_uint32 val);
extern void upmu_set_rg_chrwdt_int_en(kal_uint32 val);
extern void upmu_set_rg_chrwdt_flag_wr(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_chrwdt_out(void);
extern void upmu_set_rg_uvlo_vthl(kal_uint32 val);
extern void upmu_set_rg_usbdl_rst(kal_uint32 val);
extern void upmu_set_rg_usbdl_set(kal_uint32 val);
extern void upmu_set_adcin_vsen_mux_en(kal_uint32 val);
extern void upmu_set_rg_adcin_vsen_ext_baton_en(kal_uint32 val);
extern void upmu_set_adcin_vbat_en(kal_uint32 val);
extern void upmu_set_adcin_vsen_en(kal_uint32 val);
extern void upmu_set_adcin_vchr_en(kal_uint32 val);
extern void upmu_set_rg_bgr_rsel(kal_uint32 val);
extern void upmu_set_rg_bgr_unchop_ph(kal_uint32 val);
extern void upmu_set_rg_bgr_unchop(kal_uint32 val);
extern void upmu_set_rg_bc11_bb_ctrl(kal_uint32 val);
extern void upmu_set_rg_bc11_rst(kal_uint32 val);
extern void upmu_set_rg_bc11_vsrc_en(kal_uint32 val);
extern kal_uint32 upmu_get_rgs_bc11_cmp_out(void);
extern void upmu_set_rg_bc11_vref_vth(kal_uint32 val);
extern void upmu_set_rg_bc11_cmp_en(kal_uint32 val);
extern void upmu_set_rg_bc11_ipd_en(kal_uint32 val);
extern void upmu_set_rg_bc11_ipu_en(kal_uint32 val);
extern void upmu_set_rg_bc11_bias_en(kal_uint32 val);
extern void upmu_set_rg_csdac_stp_inc(kal_uint32 val);
extern void upmu_set_rg_csdac_stp_dec(kal_uint32 val);
extern void upmu_set_rg_csdac_dly(kal_uint32 val);
extern void upmu_set_rg_csdac_stp(kal_uint32 val);
extern void upmu_set_rg_low_ich_db(kal_uint32 val);
extern void upmu_set_rg_chrind_on(kal_uint32 val);
extern void upmu_set_rg_chrind_dimming(kal_uint32 val);
extern void upmu_set_rg_cv_mode(kal_uint32 val);
extern void upmu_set_rg_vcdt_mode(kal_uint32 val);
extern void upmu_set_rg_csdac_mode(kal_uint32 val);
extern void upmu_set_rg_tracking_en(kal_uint32 val);
extern void upmu_set_rg_hwcv_en(kal_uint32 val);
extern void upmu_set_rg_ulc_det_en(kal_uint32 val);
extern void upmu_set_rg_bgr_trim_en(kal_uint32 val);
extern void upmu_set_rg_ichrg_trim(kal_uint32 val);
extern void upmu_set_rg_bgr_trim(kal_uint32 val);
extern void upmu_set_rg_ovp_trim(kal_uint32 val);
extern void upmu_set_rg_chr_osc_trim(kal_uint32 val);
extern void upmu_set_qi_bgr_ext_buf_en(kal_uint32 val);
extern void upmu_set_rg_bgr_test_en(kal_uint32 val);
extern void upmu_set_rg_bgr_test_rstb(kal_uint32 val);
extern void upmu_set_rg_dac_usbdl_max(kal_uint32 val);
extern void upmu_set_rg_pchr_rsv(kal_uint32 val);
extern void upmu_set_thr_det_dis(kal_uint32 val);
extern void upmu_set_rg_thr_tmode(kal_uint32 val);
extern void upmu_set_rg_thr_temp_sel(kal_uint32 val);
extern void upmu_set_rg_strup_thr_sel(kal_uint32 val);
extern void upmu_set_thr_hwpdn_en(kal_uint32 val);
extern void upmu_set_rg_thrdet_sel(kal_uint32 val);
extern void upmu_set_rg_strup_iref_trim(kal_uint32 val);
extern void upmu_set_rg_usbdl_en(kal_uint32 val);
extern void upmu_set_rg_fchr_keydet_en(kal_uint32 val);
extern void upmu_set_rg_fchr_pu_en(kal_uint32 val);
extern void upmu_set_rg_en_drvsel(kal_uint32 val);
extern void upmu_set_rg_rst_drvsel(kal_uint32 val);
extern void upmu_set_rg_vref_bg(kal_uint32 val);
extern void upmu_set_rg_pmu_rsv(kal_uint32 val);
extern void upmu_set_thr_test(kal_uint32 val);
extern kal_uint32 upmu_get_pmu_thr_deb(void);
extern kal_uint32 upmu_get_pmu_thr_status(void);
extern void upmu_set_dduvlo_deb_en(kal_uint32 val);
extern void upmu_set_pwrbb_deb_en(kal_uint32 val);
extern void upmu_set_strup_osc_en(kal_uint32 val);
extern void upmu_set_strup_osc_en_sel(kal_uint32 val);
extern void upmu_set_strup_ft_ctrl(kal_uint32 val);
extern void upmu_set_strup_pwron_force(kal_uint32 val);
extern void upmu_set_bias_gen_en_force(kal_uint32 val);
extern void upmu_set_strup_pwron(kal_uint32 val);
extern void upmu_set_strup_pwron_sel(kal_uint32 val);
extern void upmu_set_bias_gen_en(kal_uint32 val);
extern void upmu_set_bias_gen_en_sel(kal_uint32 val);
extern void upmu_set_rtc_xosc32_enb_sw(kal_uint32 val);
extern void upmu_set_rtc_xosc32_enb_sel(kal_uint32 val);
extern void upmu_set_strup_dig_io_pg_force(kal_uint32 val);
extern void upmu_set_vproc_pg_enb(kal_uint32 val);
extern void upmu_set_vsys_pg_enb(kal_uint32 val);
extern void upmu_set_vm_pg_enb(kal_uint32 val);
extern void upmu_set_vio18_pg_enb(kal_uint32 val);
extern void upmu_set_vtcxo_pg_enb(kal_uint32 val);
extern void upmu_set_va_pg_enb(kal_uint32 val);
extern void upmu_set_vio28_pg_enb(kal_uint32 val);
extern void upmu_set_vgp2_pg_enb(kal_uint32 val);
extern void upmu_set_vproc_pg_h2l_en(kal_uint32 val);
extern void upmu_set_vsys_pg_h2l_en(kal_uint32 val);
extern void upmu_set_strup_con6_rsv0(kal_uint32 val);
extern void upmu_set_clr_just_rst(kal_uint32 val);
extern void upmu_set_uvlo_l2h_deb_en(kal_uint32 val);
extern kal_uint32 upmu_get_just_pwrkey_rst(void);
extern kal_uint32 upmu_get_qi_osc_en(void);
extern void upmu_set_strup_ext_pmic_en(kal_uint32 val);
extern void upmu_set_strup_ext_pmic_sel(kal_uint32 val);
extern void upmu_set_strup_con8_rsv0(kal_uint32 val);
extern kal_uint32 upmu_get_qi_ext_pmic_en(void);
extern void upmu_set_strup_auxadc_start_sw(kal_uint32 val);
extern void upmu_set_strup_auxadc_rstb_sw(kal_uint32 val);
extern void upmu_set_strup_auxadc_start_sel(kal_uint32 val);
extern void upmu_set_strup_auxadc_rstb_sel(kal_uint32 val);
extern void upmu_set_strup_pwroff_seq_en(kal_uint32 val);
extern void upmu_set_strup_pwroff_preoff_en(kal_uint32 val);
extern void upmu_set_spk_en_l(kal_uint32 val);
extern void upmu_set_spkmode_l(kal_uint32 val);
extern void upmu_set_spk_trim_en_l(kal_uint32 val);
extern void upmu_set_spk_oc_shdn_dl(kal_uint32 val);
extern void upmu_set_spk_ther_shdn_l_en(kal_uint32 val);
extern void upmu_set_rg_spk_gainl(kal_uint32 val);
extern kal_uint32 upmu_get_da_spk_offset_l(void);
extern kal_uint32 upmu_get_da_spk_lead_dglh_l(void);
extern kal_uint32 upmu_get_ni_spk_lead_l(void);
extern kal_uint32 upmu_get_spk_offset_l_ov(void);
extern void upmu_set_spk_offset_l_sw(kal_uint32 val);
extern void upmu_set_spk_lead_l_sw(kal_uint32 val);
extern void upmu_set_spk_offset_l_mode(kal_uint32 val);
extern kal_uint32 upmu_get_spk_trim_done_l(void);
extern void upmu_set_rg_spk_intg_rst_l(kal_uint32 val);
extern void upmu_set_rg_spk_force_en_l(kal_uint32 val);
extern void upmu_set_rg_spk_slew_l(kal_uint32 val);
extern void upmu_set_rg_spkab_obias_l(kal_uint32 val);
extern void upmu_set_rg_spkrcv_en_l(kal_uint32 val);
extern void upmu_set_rg_spk_drc_en_l(kal_uint32 val);
extern void upmu_set_rg_spk_test_en_l(kal_uint32 val);
extern void upmu_set_rg_spkab_oc_en_l(kal_uint32 val);
extern void upmu_set_rg_spk_oc_en_l(kal_uint32 val);
extern void upmu_set_spk_trim_wnd(kal_uint32 val);
extern void upmu_set_spk_trim_thd(kal_uint32 val);
extern void upmu_set_spk_oc_wnd(kal_uint32 val);
extern void upmu_set_spk_oc_thd(kal_uint32 val);
extern kal_uint32 upmu_get_spk_d_oc_l_deg(void);
extern kal_uint32 upmu_get_spk_ab_oc_l_deg(void);
extern void upmu_set_spk_td1(kal_uint32 val);
extern void upmu_set_spk_td2(kal_uint32 val);
extern void upmu_set_spk_td3(kal_uint32 val);
extern void upmu_set_spk_trim_div(kal_uint32 val);
extern void upmu_set_rg_btl_set(kal_uint32 val);
extern void upmu_set_rg_spk_ibias_sel(kal_uint32 val);
extern void upmu_set_rg_spk_ccode(kal_uint32 val);
extern void upmu_set_rg_spk_en_view_vcm(kal_uint32 val);
extern void upmu_set_rg_spk_en_view_clk(kal_uint32 val);
extern void upmu_set_rg_spk_vcm_sel(kal_uint32 val);
extern void upmu_set_rg_spk_vcm_ibsel(kal_uint32 val);
extern void upmu_set_rg_spk_fbrc_en(kal_uint32 val);
extern void upmu_set_rg_spkab_ovdrv(kal_uint32 val);
extern void upmu_set_rg_spk_octh_d(kal_uint32 val);
extern void upmu_set_rg_spk_rsv(kal_uint32 val);
extern void upmu_set_rg_spkpga_gain(kal_uint32 val);
extern void upmu_set_spk_rsv0(kal_uint32 val);
extern void upmu_set_spk_vcm_fast_en(kal_uint32 val);
extern void upmu_set_spk_test_mode0(kal_uint32 val);
extern void upmu_set_spk_test_mode1(kal_uint32 val);
extern void upmu_set_rg_spk_isense_refsel(kal_uint32 val);
extern void upmu_set_rg_spk_isense_gainsel(kal_uint32 val);
extern void upmu_set_rg_isense_pd_reset(kal_uint32 val);
extern void upmu_set_rg_spk_isense_en(kal_uint32 val);
extern void upmu_set_rg_spk_isense_test_en(kal_uint32 val);
extern void upmu_set_spk_td_wait(kal_uint32 val);
extern void upmu_set_spk_td_done(kal_uint32 val);
extern void upmu_set_spk_en_mode(kal_uint32 val);
extern void upmu_set_spk_vcm_fast_sw(kal_uint32 val);
extern void upmu_set_spk_rst_l_sw(kal_uint32 val);
extern void upmu_set_spkmode_l_sw(kal_uint32 val);
extern void upmu_set_spk_depop_en_l_sw(kal_uint32 val);
extern void upmu_set_spk_en_l_sw(kal_uint32 val);
extern void upmu_set_spk_outstg_en_l_sw(kal_uint32 val);
extern void upmu_set_spk_trim_en_l_sw(kal_uint32 val);
extern void upmu_set_spk_trim_stop_l_sw(kal_uint32 val);
extern kal_uint32 upmu_get_cid(void);
extern void upmu_set_rg_clksq_en_aud(kal_uint32 val);
extern void upmu_set_rg_clksq_en_aux(kal_uint32 val);
extern void upmu_set_rg_clksq_en_fqr(kal_uint32 val);
extern void upmu_set_rg_strup_75k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_strup_32k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_rtc_75k_div4_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_rtc_75k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_rtc_32k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_pchr_32k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_ldostb_1m_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_intrp_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_drv_32k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_buck_1m_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_buck_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_buck_ana_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_buck32k_pdn(kal_uint32 val);
extern void upmu_set_rg_strup_6m_pdn(kal_uint32 val);
extern void upmu_set_rg_spk_pwm_div_pdn(kal_uint32 val);
extern void upmu_set_rg_spk_div_pdn(kal_uint32 val);
extern void upmu_set_rg_spk_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_pwmoc_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_fqmtr_pdn(kal_uint32 val);
extern void upmu_set_rg_drv_2m_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_drv_1m_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_aud_26m_pdn(kal_uint32 val);
extern void upmu_set_rg_accdet_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_rtc_mclk_pdn(kal_uint32 val);
extern void upmu_set_rg_smps_ck_div_pdn(kal_uint32 val);
extern void upmu_set_rg_efuse_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_rtc32k_1v8_pdn(kal_uint32 val);
extern void upmu_set_rg_clksq_en_aux_md(kal_uint32 val);
extern void upmu_set_rg_auxadc_sdm_ck_wake_pdn(kal_uint32 val);
extern void upmu_set_rg_isink0_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_isink1_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_isink2_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_isink3_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_auxadc_sdm_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_auxadc_ctl_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_auxadc_32k_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_aud26m_div4_ck_pdn(kal_uint32 val);
extern void upmu_set_rg_efuse_man_rst(kal_uint32 val);
extern void upmu_set_rg_auxadc_rst(kal_uint32 val);
extern void upmu_set_rg_audio_rst(kal_uint32 val);
extern void upmu_set_rg_accdet_rst(kal_uint32 val);
extern void upmu_set_rg_spk_rst(kal_uint32 val);
extern void upmu_set_rg_driver_rst(kal_uint32 val);
extern void upmu_set_rg_rtc_rst(kal_uint32 val);
extern void upmu_set_rg_fqmtr_rst(kal_uint32 val);
extern void upmu_set_rg_top_rst_con_rsv_15_9(kal_uint32 val);
extern void upmu_set_rg_ap_rst_dis(kal_uint32 val);
extern void upmu_set_rg_sysrstb_en(kal_uint32 val);
extern void upmu_set_rg_strup_man_rst_en(kal_uint32 val);
extern void upmu_set_rg_newldo_rstb_en(kal_uint32 val);
extern void upmu_set_rg_rst_part_sel(kal_uint32 val);
extern void upmu_set_rg_homekey_rst_en(kal_uint32 val);
extern void upmu_set_rg_pwrkey_rst_en(kal_uint32 val);
extern void upmu_set_rg_pwrrst_tmr_dis(kal_uint32 val);
extern void upmu_set_rg_pwrkey_rst_td(kal_uint32 val);
extern void upmu_set_rg_srclken_en(kal_uint32 val);
extern void upmu_set_rg_osc_sel(kal_uint32 val);
extern void upmu_set_rg_auxadc_sdm_sel_hw_mode(kal_uint32 val);
extern void upmu_set_rg_srclken_hw_mode(kal_uint32 val);
extern void upmu_set_rg_osc_hw_mode(kal_uint32 val);
extern void upmu_set_rg_osc_hw_src_sel(kal_uint32 val);
extern void upmu_set_rg_auxadc_sdm_ck_hw_mode(kal_uint32 val);
extern void upmu_set_rg_smps_autoff_dis(kal_uint32 val);
extern void upmu_set_rg_buck_1m_autoff_dis(kal_uint32 val);
extern void upmu_set_rg_buck_ana_autoff_dis(kal_uint32 val);
extern void upmu_set_rg_regck_sel(kal_uint32 val);
extern void upmu_set_rg_spk_pwm_div_sel(kal_uint32 val);
extern void upmu_set_rg_spk_div_sel(kal_uint32 val);
extern void upmu_set_rg_fqmtr_cksel(kal_uint32 val);
extern void upmu_set_rg_accdet_cksel(kal_uint32 val);
extern void upmu_set_rg_isink0_ck_sel(kal_uint32 val);
extern void upmu_set_rg_isink1_ck_sel(kal_uint32 val);
extern void upmu_set_rg_isink2_ck_sel(kal_uint32 val);
extern void upmu_set_rg_isink3_ck_sel(kal_uint32 val);
extern void upmu_set_rg_auxadc_sdm_ck_sel(kal_uint32 val);
extern void upmu_set_rg_audio_ck_sel(kal_uint32 val);
extern void upmu_set_rg_rtc32k_tst_dis(kal_uint32 val);
extern void upmu_set_rg_spk_tst_dis(kal_uint32 val);
extern void upmu_set_rg_smps_tst_dis(kal_uint32 val);
extern void upmu_set_rg_pmu75k_tst_dis(kal_uint32 val);
extern void upmu_set_rg_aud26m_tst_dis(kal_uint32 val);
extern void upmu_set_rg_spk_tstsel(kal_uint32 val);
extern void upmu_set_rg_smps_tstsel(kal_uint32 val);
extern void upmu_set_rg_rtc32k_tstsel(kal_uint32 val);
extern void upmu_set_rg_pmu75k_tstsel(kal_uint32 val);
extern void upmu_set_rg_aud26m_tstsel(kal_uint32 val);
extern void upmu_set_rg_rtcdet_tstsel(kal_uint32 val);
extern void upmu_set_rg_pwmoc_tstsel(kal_uint32 val);
extern void upmu_set_rg_ldostb_tstsel(kal_uint32 val);
extern void upmu_set_rg_isink_tstsel(kal_uint32 val);
extern void upmu_set_rg_fqmtr_tstsel(kal_uint32 val);
extern void upmu_set_rg_classd_tstsel(kal_uint32 val);
extern void upmu_set_rg_auxadc_sdm_tstsel(kal_uint32 val);
extern void upmu_set_rg_aud26m_div4_tstsel(kal_uint32 val);
extern void upmu_set_rg_audif_tstsel(kal_uint32 val);
extern void upmu_set_rg_bgr_test_ck_sel(kal_uint32 val);
extern void upmu_set_rg_pchr_test_ck_sel(kal_uint32 val);
extern void upmu_set_rg_strup_75k_26m_sel(kal_uint32 val);
extern void upmu_set_rg_bgr_testmode(kal_uint32 val);
extern void upmu_set_rg_top_cktst2_rsv_15_8(kal_uint32 val);
extern kal_uint32 upmu_get_test_out(void);
extern void upmu_set_rg_mon_flag_sel(kal_uint32 val);
extern void upmu_set_rg_mon_grp_sel(kal_uint32 val);
extern void upmu_set_rg_test_driver(kal_uint32 val);
extern void upmu_set_rg_test_classd(kal_uint32 val);
extern void upmu_set_rg_test_aud(kal_uint32 val);
extern void upmu_set_rg_test_auxadc(kal_uint32 val);
extern void upmu_set_rg_nandtree_mode(kal_uint32 val);
extern void upmu_set_rg_efuse_mode(kal_uint32 val);
extern void upmu_set_rg_test_strup(kal_uint32 val);
extern void upmu_set_rg_test_spk(kal_uint32 val);
extern void upmu_set_rg_test_spk_pwm(kal_uint32 val);
extern kal_uint32 upmu_get_en_status_vproc(void);
extern kal_uint32 upmu_get_en_status_vsys(void);
extern kal_uint32 upmu_get_en_status_vpa(void);
extern kal_uint32 upmu_get_en_status_vrtc(void);
extern kal_uint32 upmu_get_en_status_va(void);
extern kal_uint32 upmu_get_en_status_vcama(void);
extern kal_uint32 upmu_get_en_status_vcamd(void);
extern kal_uint32 upmu_get_en_status_vcam_af(void);
extern kal_uint32 upmu_get_en_status_vcam_io(void);
extern kal_uint32 upmu_get_en_status_vcn28(void);
extern kal_uint32 upmu_get_en_status_vcn33(void);
extern kal_uint32 upmu_get_en_status_vcn_1v8(void);
extern kal_uint32 upmu_get_en_status_vemc_3v3(void);
extern kal_uint32 upmu_get_en_status_vgp1(void);
extern kal_uint32 upmu_get_en_status_vgp2(void);
extern kal_uint32 upmu_get_en_status_vgp3(void);
extern kal_uint32 upmu_get_en_status_vibr(void);
extern kal_uint32 upmu_get_en_status_vio18(void);
extern kal_uint32 upmu_get_en_status_vio28(void);
extern kal_uint32 upmu_get_en_status_vm(void);
extern kal_uint32 upmu_get_en_status_vmc(void);
extern kal_uint32 upmu_get_en_status_vmch(void);
extern kal_uint32 upmu_get_en_status_vrf18(void);
extern kal_uint32 upmu_get_en_status_vsim1(void);
extern kal_uint32 upmu_get_en_status_vsim2(void);
extern kal_uint32 upmu_get_en_status_vtcxo(void);
extern kal_uint32 upmu_get_en_status_vusb(void);
extern kal_uint32 upmu_get_oc_status_vproc(void);
extern kal_uint32 upmu_get_oc_status_vsys(void);
extern kal_uint32 upmu_get_oc_status_vpa(void);
extern kal_uint32 upmu_get_oc_status_va(void);
extern kal_uint32 upmu_get_oc_status_vcama(void);
extern kal_uint32 upmu_get_oc_status_vcamd(void);
extern kal_uint32 upmu_get_oc_status_vcam_af(void);
extern kal_uint32 upmu_get_oc_status_vcam_io(void);
extern kal_uint32 upmu_get_oc_status_vcn28(void);
extern kal_uint32 upmu_get_oc_status_vcn33(void);
extern kal_uint32 upmu_get_oc_status_vcn_1v8(void);
extern kal_uint32 upmu_get_oc_status_vemc_3v3(void);
extern kal_uint32 upmu_get_oc_status_vgp1(void);
extern kal_uint32 upmu_get_oc_status_vgp2(void);
extern kal_uint32 upmu_get_oc_status_vgp3(void);
extern kal_uint32 upmu_get_oc_status_vibr(void);
extern kal_uint32 upmu_get_oc_status_vio18(void);
extern kal_uint32 upmu_get_oc_status_vio28(void);
extern kal_uint32 upmu_get_oc_status_vm(void);
extern kal_uint32 upmu_get_oc_status_vmc(void);
extern kal_uint32 upmu_get_oc_status_vmch(void);
extern kal_uint32 upmu_get_oc_status_vrf18(void);
extern kal_uint32 upmu_get_oc_status_vsim1(void);
extern kal_uint32 upmu_get_oc_status_vsim2(void);
extern kal_uint32 upmu_get_oc_status_vtcxo(void);
extern kal_uint32 upmu_get_oc_status_vusb(void);
extern kal_uint32 upmu_get_ni_spk_oc_det_d_l(void);
extern kal_uint32 upmu_get_ni_spk_oc_det_ab_l(void);
extern kal_uint32 upmu_get_vproc_pg_deb(void);
extern kal_uint32 upmu_get_vsys_pg_deb(void);
extern kal_uint32 upmu_get_vm_pg_deb(void);
extern kal_uint32 upmu_get_vio18_pg_deb(void);
extern kal_uint32 upmu_get_vtcxo_pg_deb(void);
extern kal_uint32 upmu_get_va_pg_deb(void);
extern kal_uint32 upmu_get_vio28_pg_deb(void);
extern kal_uint32 upmu_get_vgp2_pg_deb(void);
extern kal_uint32 upmu_get_pmu_test_mode_scan(void);
extern kal_uint32 upmu_get_pwrkey_deb(void);
extern kal_uint32 upmu_get_fchrkey_deb(void);
extern kal_uint32 upmu_get_vbat_ov(void);
extern kal_uint32 upmu_get_pchr_chrdet(void);
extern kal_uint32 upmu_get_ro_baton_undet(void);
extern kal_uint32 upmu_get_rtc_xtal_det_done(void);
extern kal_uint32 upmu_get_xosc32_enb_det(void);
extern void upmu_set_rtc_xtal_det_rsv(kal_uint32 val);
extern void upmu_set_rg_simap_tdsel(kal_uint32 val);
extern void upmu_set_rg_aud_tdsel(kal_uint32 val);
extern void upmu_set_rg_spi_tdsel(kal_uint32 val);
extern void upmu_set_rg_pmu_tdsel(kal_uint32 val);
extern void upmu_set_rg_simls_tdsel(kal_uint32 val);
extern void upmu_set_rg_simap_rdsel(kal_uint32 val);
extern void upmu_set_rg_aud_rdsel(kal_uint32 val);
extern void upmu_set_rg_spi_rdsel(kal_uint32 val);
extern void upmu_set_rg_pmu_rdsel(kal_uint32 val);
extern void upmu_set_rg_simls_rdsel(kal_uint32 val);
extern void upmu_set_rg_smt_sysrstb(kal_uint32 val);
extern void upmu_set_rg_smt_int(kal_uint32 val);
extern void upmu_set_rg_smt_srclken(kal_uint32 val);
extern void upmu_set_rg_smt_rtc_32k1v8(kal_uint32 val);
extern void upmu_set_rg_smt_spi_clk(kal_uint32 val);
extern void upmu_set_rg_smt_spi_csn(kal_uint32 val);
extern void upmu_set_rg_smt_spi_mosi(kal_uint32 val);
extern void upmu_set_rg_smt_spi_miso(kal_uint32 val);
extern void upmu_set_rg_smt_aud_clk(kal_uint32 val);
extern void upmu_set_rg_smt_aud_mosi(kal_uint32 val);
extern void upmu_set_rg_smt_aud_miso(kal_uint32 val);
extern void upmu_set_rg_smt_sim1_ap_sclk(kal_uint32 val);
extern void upmu_set_rg_smt_sim1_ap_srst(kal_uint32 val);
extern void upmu_set_rg_smt_simls1_sclk(kal_uint32 val);
extern void upmu_set_rg_smt_simls1_srst(kal_uint32 val);
extern void upmu_set_rg_smt_sim2_ap_sclk(kal_uint32 val);
extern void upmu_set_rg_smt_sim2_ap_srst(kal_uint32 val);
extern void upmu_set_rg_smt_simls2_sclk(kal_uint32 val);
extern void upmu_set_rg_smt_simls2_srst(kal_uint32 val);
extern void upmu_set_rg_octl_int(kal_uint32 val);
extern void upmu_set_rg_octl_srclken(kal_uint32 val);
extern void upmu_set_rg_octl_rtc_32k1v8(kal_uint32 val);
extern void upmu_set_rg_octl_spi_clk(kal_uint32 val);
extern void upmu_set_rg_octl_spi_csn(kal_uint32 val);
extern void upmu_set_rg_octl_spi_mosi(kal_uint32 val);
extern void upmu_set_rg_octl_spi_miso(kal_uint32 val);
extern void upmu_set_rg_octl_aud_clk(kal_uint32 val);
extern void upmu_set_rg_octl_aud_mosi(kal_uint32 val);
extern void upmu_set_rg_octl_aud_miso(kal_uint32 val);
extern void upmu_set_rg_octl_sim1_ap_sclk(kal_uint32 val);
extern void upmu_set_rg_octl_sim1_ap_srst(kal_uint32 val);
extern void upmu_set_rg_octl_simls1_sclk(kal_uint32 val);
extern void upmu_set_rg_octl_simls1_srst(kal_uint32 val);
extern void upmu_set_rg_octl_sim2_ap_sclk(kal_uint32 val);
extern void upmu_set_rg_octl_sim2_ap_srst(kal_uint32 val);
extern void upmu_set_rg_octl_simls2_sclk(kal_uint32 val);
extern void upmu_set_rg_octl_simls2_srst(kal_uint32 val);
extern void upmu_set_rg_simls1_sclk_conf(kal_uint32 val);
extern void upmu_set_rg_simls1_srst_conf(kal_uint32 val);
extern void upmu_set_rg_simls2_sclk_conf(kal_uint32 val);
extern void upmu_set_rg_simls2_srst_conf(kal_uint32 val);
extern void upmu_set_rg_int_en_spkl_ab(kal_uint32 val);
extern void upmu_set_rg_int_en_spkl(kal_uint32 val);
extern void upmu_set_rg_int_en_bat_l(kal_uint32 val);
extern void upmu_set_rg_int_en_bat_h(kal_uint32 val);
extern void upmu_set_rg_int_en_watchdog(kal_uint32 val);
extern void upmu_set_rg_int_en_pwrkey(kal_uint32 val);
extern void upmu_set_rg_int_en_thr_l(kal_uint32 val);
extern void upmu_set_rg_int_en_thr_h(kal_uint32 val);
extern void upmu_set_rg_int_en_vbaton_undet(kal_uint32 val);
extern void upmu_set_rg_int_en_bvalid_det(kal_uint32 val);
extern void upmu_set_rg_int_en_chrdet(kal_uint32 val);
extern void upmu_set_rg_int_en_ov(kal_uint32 val);
extern void upmu_set_rg_int_en_ldo(kal_uint32 val);
extern void upmu_set_rg_int_en_fchrkey(kal_uint32 val);
extern void upmu_set_rg_int_en_accdet(kal_uint32 val);
extern void upmu_set_rg_int_en_audio(kal_uint32 val);
extern void upmu_set_rg_int_en_rtc(kal_uint32 val);
extern void upmu_set_rg_int_en_vproc(kal_uint32 val);
extern void upmu_set_rg_int_en_vsys(kal_uint32 val);
extern void upmu_set_rg_int_en_vpa(kal_uint32 val);
extern void upmu_set_polarity(kal_uint32 val);
extern void upmu_set_polarity_vbaton_undet(kal_uint32 val);
extern void upmu_set_polarity_bvalid_det(kal_uint32 val);
extern void upmu_set_rg_fchrkey_int_sel(kal_uint32 val);
extern void upmu_set_rg_pwrkey_int_sel(kal_uint32 val);
extern void upmu_set_ivgen_ext_en(kal_uint32 val);
extern kal_uint32 upmu_get_rg_int_status_spkl_ab(void);
extern kal_uint32 upmu_get_rg_int_status_spkl(void);
extern kal_uint32 upmu_get_rg_int_status_bat_l(void);
extern kal_uint32 upmu_get_rg_int_status_bat_h(void);
extern kal_uint32 upmu_get_rg_int_status_watchdog(void);
extern kal_uint32 upmu_get_rg_int_status_pwrkey(void);
extern kal_uint32 upmu_get_rg_int_status_thr_l(void);
extern kal_uint32 upmu_get_rg_int_status_thr_h(void);
extern kal_uint32 upmu_get_rg_int_status_vbaton_undet(void);
extern kal_uint32 upmu_get_rg_int_status_bvalid_det(void);
extern kal_uint32 upmu_get_rg_int_status_chrdet(void);
extern kal_uint32 upmu_get_rg_int_status_ov(void);
extern kal_uint32 upmu_get_rg_int_status_ldo(void);
extern kal_uint32 upmu_get_rg_int_status_fchrkey(void);
extern kal_uint32 upmu_get_rg_int_status_accdet(void);
extern kal_uint32 upmu_get_rg_int_status_audio(void);
extern kal_uint32 upmu_get_rg_int_status_rtc(void);
extern kal_uint32 upmu_get_rg_int_status_vproc(void);
extern kal_uint32 upmu_get_rg_int_status_vsys(void);
extern kal_uint32 upmu_get_rg_int_status_vpa(void);
extern void upmu_set_oc_gear_bvalid_det(kal_uint32 val);
extern void upmu_set_oc_gear_vbaton_undet(kal_uint32 val);
extern void upmu_set_oc_gear_ldo(kal_uint32 val);
extern void upmu_set_vproc_oc_thd(kal_uint32 val);
extern void upmu_set_vproc_oc_wnd(kal_uint32 val);
extern void upmu_set_vproc_deg_en(kal_uint32 val);
extern void upmu_set_vsys_oc_thd(kal_uint32 val);
extern void upmu_set_vsys_oc_wnd(kal_uint32 val);
extern void upmu_set_vsys_deg_en(kal_uint32 val);
extern void upmu_set_vpa_oc_thd(kal_uint32 val);
extern void upmu_set_vpa_oc_wnd(kal_uint32 val);
extern void upmu_set_vpa_deg_en(kal_uint32 val);
extern void upmu_set_fqmtr_tcksel(kal_uint32 val);
extern kal_uint32 upmu_get_fqmtr_busy(void);
extern void upmu_set_fqmtr_en(kal_uint32 val);
extern void upmu_set_fqmtr_winset(kal_uint32 val);
extern kal_uint32 upmu_get_fqmtr_data(void);
extern void upmu_set_rg_spi_con(kal_uint32 val);
extern void upmu_set_dew_dio_en(kal_uint32 val);
extern kal_uint32 upmu_get_dew_read_test(void);
extern void upmu_set_dew_write_test(kal_uint32 val);
extern void upmu_set_dew_crc_swrst(kal_uint32 val);
extern void upmu_set_dew_crc_en(kal_uint32 val);
extern kal_uint32 upmu_get_dew_crc_val(void);
extern void upmu_set_dew_dbg_mon_sel(kal_uint32 val);
extern void upmu_set_dew_cipher_key_sel(kal_uint32 val);
extern void upmu_set_dew_cipher_iv_sel(kal_uint32 val);
extern void upmu_set_dew_cipher_en(kal_uint32 val);
extern kal_uint32 upmu_get_dew_cipher_rdy(void);
extern void upmu_set_dew_cipher_mode(kal_uint32 val);
extern void upmu_set_dew_cipher_swrst(kal_uint32 val);
extern void upmu_set_dew_rddmy_no(kal_uint32 val);
extern void upmu_set_dew_rdata_dly_sel(kal_uint32 val);
extern void upmu_set_rg_smps_testmode_b(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vproc_dig_mon(void);
extern kal_uint32 upmu_get_qi_vsys_dig_mon(void);
extern void upmu_set_vsleep_src0(kal_uint32 val);
extern void upmu_set_vsleep_src1(kal_uint32 val);
extern void upmu_set_r2r_src0(kal_uint32 val);
extern void upmu_set_r2r_src1(kal_uint32 val);
extern void upmu_set_buck_osc_sel_src0(kal_uint32 val);
extern void upmu_set_srclken_dly_src1(kal_uint32 val);
extern void upmu_set_buck_con5_rsv0(kal_uint32 val);
extern void upmu_set_rg_vproc_triml(kal_uint32 val);
extern void upmu_set_rg_vproc_trimh(kal_uint32 val);
extern void upmu_set_rg_vproc_csm(kal_uint32 val);
extern void upmu_set_rg_vproc_zxos_trim(kal_uint32 val);
extern void upmu_set_rg_vproc_rzsel(kal_uint32 val);
extern void upmu_set_rg_vproc_cc(kal_uint32 val);
extern void upmu_set_rg_vproc_csr(kal_uint32 val);
extern void upmu_set_rg_vproc_csl(kal_uint32 val);
extern void upmu_set_rg_vproc_zx_os(kal_uint32 val);
extern void upmu_set_rg_vproc_avp_os(kal_uint32 val);
extern void upmu_set_rg_vproc_avp_en(kal_uint32 val);
extern void upmu_set_rg_vproc_modeset(kal_uint32 val);
extern void upmu_set_rg_vproc_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vproc_slp(kal_uint32 val);
extern void upmu_set_qi_vproc_vsleep(kal_uint32 val);
extern void upmu_set_rg_vproc_rsv(kal_uint32 val);
extern void upmu_set_vproc_en_ctrl(kal_uint32 val);
extern void upmu_set_vproc_vosel_ctrl(kal_uint32 val);
extern void upmu_set_vproc_dlc_ctrl(kal_uint32 val);
extern void upmu_set_vproc_burst_ctrl(kal_uint32 val);
extern void upmu_set_vproc_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vproc_stb(void);
extern kal_uint32 upmu_get_qi_vproc_en(void);
extern kal_uint32 upmu_get_qi_vproc_oc_status(void);
extern void upmu_set_vproc_sfchg_frate(kal_uint32 val);
extern void upmu_set_vproc_sfchg_fen(kal_uint32 val);
extern void upmu_set_vproc_sfchg_rrate(kal_uint32 val);
extern void upmu_set_vproc_sfchg_ren(kal_uint32 val);
extern void upmu_set_vproc_vosel(kal_uint32 val);
extern void upmu_set_vproc_vosel_on(kal_uint32 val);
extern void upmu_set_vproc_vosel_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vproc_vosel(void);
extern void upmu_set_vproc_burst(kal_uint32 val);
extern void upmu_set_vproc_burst_on(kal_uint32 val);
extern void upmu_set_vproc_burst_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vproc_burst(void);
extern void upmu_set_vproc_dlc(kal_uint32 val);
extern void upmu_set_vproc_dlc_on(kal_uint32 val);
extern void upmu_set_vproc_dlc_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vproc_dlc(void);
extern void upmu_set_vproc_dlc_n(kal_uint32 val);
extern void upmu_set_vproc_dlc_n_on(kal_uint32 val);
extern void upmu_set_vproc_dlc_n_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vproc_dlc_n(void);
extern void upmu_set_vproc_transtd(kal_uint32 val);
extern void upmu_set_vproc_vosel_trans_en(kal_uint32 val);
extern void upmu_set_vproc_vosel_trans_once(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vproc_vosel_trans(void);
extern void upmu_set_vproc_vsleep_en(kal_uint32 val);
extern void upmu_set_vproc_r2r_pdn(kal_uint32 val);
extern void upmu_set_vproc_vsleep_sel(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vproc_r2r_pdn(void);
extern kal_uint32 upmu_get_ni_vproc_vsleep_sel(void);
extern void upmu_set_rg_vsys_triml(kal_uint32 val);
extern void upmu_set_rg_vsys_trimh(kal_uint32 val);
extern void upmu_set_rg_vsys_csm(kal_uint32 val);
extern void upmu_set_rg_vsys_zxos_trim(kal_uint32 val);
extern void upmu_set_rg_vsys_rzsel(kal_uint32 val);
extern void upmu_set_rg_vsys_cc(kal_uint32 val);
extern void upmu_set_rg_vsys_csr(kal_uint32 val);
extern void upmu_set_rg_vsys_csl(kal_uint32 val);
extern void upmu_set_rg_vsys_zx_os(kal_uint32 val);
extern void upmu_set_rg_vsys_avp_os(kal_uint32 val);
extern void upmu_set_rg_vsys_avp_en(kal_uint32 val);
extern void upmu_set_rg_vsys_modeset(kal_uint32 val);
extern void upmu_set_rg_vsys_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vsys_slp(kal_uint32 val);
extern void upmu_set_qi_vsys_vsleep(kal_uint32 val);
extern void upmu_set_rg_vsys_rsv(kal_uint32 val);
extern void upmu_set_vsys_en_ctrl(kal_uint32 val);
extern void upmu_set_vsys_vosel_ctrl(kal_uint32 val);
extern void upmu_set_vsys_dlc_ctrl(kal_uint32 val);
extern void upmu_set_vsys_burst_ctrl(kal_uint32 val);
extern void upmu_set_vsys_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vsys_stb(void);
extern kal_uint32 upmu_get_qi_vsys_en(void);
extern kal_uint32 upmu_get_qi_vsys_oc_status(void);
extern void upmu_set_vsys_sfchg_frate(kal_uint32 val);
extern void upmu_set_vsys_sfchg_fen(kal_uint32 val);
extern void upmu_set_vsys_sfchg_rrate(kal_uint32 val);
extern void upmu_set_vsys_sfchg_ren(kal_uint32 val);
extern void upmu_set_vsys_vosel(kal_uint32 val);
extern void upmu_set_vsys_vosel_on(kal_uint32 val);
extern void upmu_set_vsys_vosel_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vsys_vosel(void);
extern void upmu_set_vsys_burst(kal_uint32 val);
extern void upmu_set_vsys_burst_on(kal_uint32 val);
extern void upmu_set_vsys_burst_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vsys_burst(void);
extern void upmu_set_vsys_dlc(kal_uint32 val);
extern void upmu_set_vsys_dlc_on(kal_uint32 val);
extern void upmu_set_vsys_dlc_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vsys_dlc(void);
extern void upmu_set_vsys_dlc_n(kal_uint32 val);
extern void upmu_set_vsys_dlc_n_on(kal_uint32 val);
extern void upmu_set_vsys_dlc_n_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vsys_dlc_n(void);
extern void upmu_set_vsys_transtd(kal_uint32 val);
extern void upmu_set_vsys_vosel_trans_en(kal_uint32 val);
extern void upmu_set_vsys_vosel_trans_once(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vsys_vosel_trans(void);
extern void upmu_set_vsys_vsleep_en(kal_uint32 val);
extern void upmu_set_vsys_r2r_pdn(kal_uint32 val);
extern void upmu_set_vsys_vsleep_sel(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vsys_r2r_pdn(void);
extern kal_uint32 upmu_get_ni_vsys_vsleep_sel(void);
extern void upmu_set_rg_vpa_triml(kal_uint32 val);
extern void upmu_set_rg_vpa_trimh(kal_uint32 val);
extern void upmu_set_rg_vpa_rzsel(kal_uint32 val);
extern void upmu_set_rg_vpa_cc(kal_uint32 val);
extern void upmu_set_rg_vpa_csr(kal_uint32 val);
extern void upmu_set_rg_vpa_csl(kal_uint32 val);
extern void upmu_set_rg_vpa_slew_nmos(kal_uint32 val);
extern void upmu_set_rg_vpa_slew(kal_uint32 val);
extern void upmu_set_rg_vpa_zx_os(kal_uint32 val);
extern void upmu_set_rg_vpa_modeset(kal_uint32 val);
extern void upmu_set_rg_vpa_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vpa_csmir(kal_uint32 val);
extern void upmu_set_rg_vpa_vbat_del(kal_uint32 val);
extern void upmu_set_rg_vpa_slp(kal_uint32 val);
extern void upmu_set_rg_vpa_gpu_en(kal_uint32 val);
extern void upmu_set_rg_vpa_rsv(kal_uint32 val);
extern void upmu_set_vpa_en_ctrl(kal_uint32 val);
extern void upmu_set_vpa_vosel_ctrl(kal_uint32 val);
extern void upmu_set_vpa_dlc_ctrl(kal_uint32 val);
extern void upmu_set_vpa_burst_ctrl(kal_uint32 val);
extern void upmu_set_vpa_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vpa_stb(void);
extern kal_uint32 upmu_get_qi_vpa_en(void);
extern kal_uint32 upmu_get_qi_vpa_oc_status(void);
extern void upmu_set_vpa_sfchg_frate(kal_uint32 val);
extern void upmu_set_vpa_sfchg_fen(kal_uint32 val);
extern void upmu_set_vpa_sfchg_rrate(kal_uint32 val);
extern void upmu_set_vpa_sfchg_ren(kal_uint32 val);
extern void upmu_set_vpa_vosel(kal_uint32 val);
extern void upmu_set_vpa_vosel_on(kal_uint32 val);
extern void upmu_set_vpa_vosel_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vpa_vosel(void);
extern void upmu_set_vpa_dlc(kal_uint32 val);
extern void upmu_set_vpa_dlc_on(kal_uint32 val);
extern void upmu_set_vpa_dlc_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vpa_dlc(void);
extern void upmu_set_vpa_bursth(kal_uint32 val);
extern void upmu_set_vpa_bursth_on(kal_uint32 val);
extern void upmu_set_vpa_bursth_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vpa_bursth(void);
extern void upmu_set_vpa_burstl(kal_uint32 val);
extern void upmu_set_vpa_burstl_on(kal_uint32 val);
extern void upmu_set_vpa_burstl_sleep(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vpa_burstl(void);
extern void upmu_set_vpa_transtd(kal_uint32 val);
extern void upmu_set_vpa_vosel_trans_en(kal_uint32 val);
extern void upmu_set_vpa_vosel_trans_once(kal_uint32 val);
extern kal_uint32 upmu_get_ni_vpa_dvs_bw(void);
extern void upmu_set_vpa_dlc_map_en(kal_uint32 val);
extern void upmu_set_vpa_vosel_dlc001(kal_uint32 val);
extern void upmu_set_vpa_vosel_dlc011(kal_uint32 val);
extern void upmu_set_vpa_vosel_dlc111(kal_uint32 val);
extern void upmu_set_k_rst_done(kal_uint32 val);
extern void upmu_set_k_map_sel(kal_uint32 val);
extern void upmu_set_k_once_en(kal_uint32 val);
extern void upmu_set_k_once(kal_uint32 val);
extern void upmu_set_k_start_manual(kal_uint32 val);
extern void upmu_set_k_src_sel(kal_uint32 val);
extern void upmu_set_k_auto_en(kal_uint32 val);
extern void upmu_set_k_inv(kal_uint32 val);
extern void upmu_set_k_control_smps(kal_uint32 val);
extern kal_uint32 upmu_get_k_result(void);
extern kal_uint32 upmu_get_k_done(void);
extern kal_uint32 upmu_get_k_control(void);
extern kal_uint32 upmu_get_qi_smps_osc_cal(void);
extern void upmu_set_isink_ch0_mode(kal_uint32 val);
extern void upmu_set_isink0_rsv1(kal_uint32 val);
extern void upmu_set_isink_dim0_duty(kal_uint32 val);
extern void upmu_set_isink0_rsv0(kal_uint32 val);
extern void upmu_set_isink_dim0_fsel(kal_uint32 val);
extern void upmu_set_isink_sfstr0_en(kal_uint32 val);
extern void upmu_set_isink_sfstr0_tc(kal_uint32 val);
extern void upmu_set_isink_ch0_step(kal_uint32 val);
extern void upmu_set_isink_breath0_toff_sel(kal_uint32 val);
extern void upmu_set_isink_breath0_ton_sel(kal_uint32 val);
extern void upmu_set_isink_breath0_trf_sel(kal_uint32 val);
extern void upmu_set_isink_ch1_mode(kal_uint32 val);
extern void upmu_set_isink1_rsv1(kal_uint32 val);
extern void upmu_set_isink_dim1_duty(kal_uint32 val);
extern void upmu_set_isink1_rsv0(kal_uint32 val);
extern void upmu_set_isink_dim1_fsel(kal_uint32 val);
extern void upmu_set_isink_sfstr1_en(kal_uint32 val);
extern void upmu_set_isink_sfstr1_tc(kal_uint32 val);
extern void upmu_set_isink_ch1_step(kal_uint32 val);
extern void upmu_set_isink_breath1_toff_sel(kal_uint32 val);
extern void upmu_set_isink_breath1_ton_sel(kal_uint32 val);
extern void upmu_set_isink_breath1_trf_sel(kal_uint32 val);
extern void upmu_set_isink_ch2_mode(kal_uint32 val);
extern void upmu_set_isink2_rsv1(kal_uint32 val);
extern void upmu_set_isink_dim2_duty(kal_uint32 val);
extern void upmu_set_isink2_rsv0(kal_uint32 val);
extern void upmu_set_isink_dim2_fsel(kal_uint32 val);
extern void upmu_set_isink_sfstr2_en(kal_uint32 val);
extern void upmu_set_isink_sfstr2_tc(kal_uint32 val);
extern void upmu_set_isink_ch2_step(kal_uint32 val);
extern void upmu_set_isink_breath2_toff_sel(kal_uint32 val);
extern void upmu_set_isink_breath2_ton_sel(kal_uint32 val);
extern void upmu_set_isink_breath2_trf_sel(kal_uint32 val);
extern void upmu_set_isink_ch3_mode(kal_uint32 val);
extern void upmu_set_isink3_rsv1(kal_uint32 val);
extern void upmu_set_isink_dim3_duty(kal_uint32 val);
extern void upmu_set_isink3_rsv0(kal_uint32 val);
extern void upmu_set_isink_dim3_fsel(kal_uint32 val);
extern void upmu_set_isink_sfstr3_en(kal_uint32 val);
extern void upmu_set_isink_sfstr3_tc(kal_uint32 val);
extern void upmu_set_isink_ch3_step(kal_uint32 val);
extern void upmu_set_isink_breath3_toff_sel(kal_uint32 val);
extern void upmu_set_isink_breath3_ton_sel(kal_uint32 val);
extern void upmu_set_isink_breath3_trf_sel(kal_uint32 val);
extern void upmu_set_rg_isinks_rsv(kal_uint32 val);
extern void upmu_set_rg_isink3_double_en(kal_uint32 val);
extern void upmu_set_rg_isink2_double_en(kal_uint32 val);
extern void upmu_set_rg_isink1_double_en(kal_uint32 val);
extern void upmu_set_rg_isink0_double_en(kal_uint32 val);
extern void upmu_set_rg_trim_sel(kal_uint32 val);
extern void upmu_set_rg_trim_en(kal_uint32 val);
extern kal_uint32 upmu_get_ni_isink3_status(void);
extern kal_uint32 upmu_get_ni_isink2_status(void);
extern kal_uint32 upmu_get_ni_isink1_status(void);
extern kal_uint32 upmu_get_ni_isink0_status(void);
extern void upmu_set_isink_phase0_dly_en(kal_uint32 val);
extern void upmu_set_isink_phase1_dly_en(kal_uint32 val);
extern void upmu_set_isink_phase2_dly_en(kal_uint32 val);
extern void upmu_set_isink_phase3_dly_en(kal_uint32 val);
extern void upmu_set_isink_phase_dly_tc(kal_uint32 val);
extern void upmu_set_isink_ch0_en(kal_uint32 val);
extern void upmu_set_isink_ch1_en(kal_uint32 val);
extern void upmu_set_isink_ch2_en(kal_uint32 val);
extern void upmu_set_isink_ch3_en(kal_uint32 val);
extern void upmu_set_isink_chop0_en(kal_uint32 val);
extern void upmu_set_isink_chop1_en(kal_uint32 val);
extern void upmu_set_isink_chop2_en(kal_uint32 val);
extern void upmu_set_isink_chop3_en(kal_uint32 val);
extern void upmu_set_rg_analdorsv1(kal_uint32 val);
extern void upmu_set_vtcxo_lp_sel(kal_uint32 val);
extern void upmu_set_vtcxo_lp_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vtcxo_mode(void);
extern void upmu_set_rg_vtcxo_stbtd(kal_uint32 val);
extern void upmu_set_rg_vtcxo_en(kal_uint32 val);
extern void upmu_set_vtcxo_on_ctrl(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vtcxo_en(void);
extern void upmu_set_va_lp_sel(kal_uint32 val);
extern void upmu_set_va_lp_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_va_mode(void);
extern void upmu_set_rg_va_sense_sel(kal_uint32 val);
extern void upmu_set_rg_va_stbtd(kal_uint32 val);
extern void upmu_set_rg_va_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_va_en(void);
extern void upmu_set_rg_analdorsv2(kal_uint32 val);
extern void upmu_set_rg_vcama_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcama_en(kal_uint32 val);
extern void upmu_set_rg_vcama_bist_en(kal_uint32 val);
extern void upmu_set_rg_va_bist_en(kal_uint32 val);
extern void upmu_set_rg_vtcxo_bist_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcama_oc_status(void);
extern kal_uint32 upmu_get_qi_va_oc_status(void);
extern kal_uint32 upmu_get_qi_vtcxo_oc_status(void);
extern void upmu_set_rg_analdorsv3(kal_uint32 val);
extern void upmu_set_rg_vtcxo_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vtcxo_ocfb(kal_uint32 val);
extern void upmu_set_rg_vtcxo_cal(kal_uint32 val);
extern void upmu_set_rg_va_ndis_en(kal_uint32 val);
extern void upmu_set_rg_va_ocfb(kal_uint32 val);
extern void upmu_set_rg_va_vosel(kal_uint32 val);
extern void upmu_set_rg_va_cal(kal_uint32 val);
extern void upmu_set_rg_vcama_fbsel(kal_uint32 val);
extern void upmu_set_rg_vcama_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vcama_ocfb(kal_uint32 val);
extern void upmu_set_rg_vcama_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vcama_vosel(kal_uint32 val);
extern void upmu_set_vcama_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vcama_cal(kal_uint32 val);
extern void upmu_set_rg_reserve_stb_sel(kal_uint32 val);
extern void upmu_set_rg_aldo_reserve(kal_uint32 val);
extern void upmu_set_rg_vcn33_vosel(kal_uint32 val);
extern void upmu_set_rg_vcn33_ndis_en(kal_uint32 val);
extern void upmu_set_vcn33_on_ctrl_bt(kal_uint32 val);
extern void upmu_set_rg_vcn33_ocfb(kal_uint32 val);
extern void upmu_set_rg_vcn33_en_bt(kal_uint32 val);
extern void upmu_set_rg_vcn33_cal(kal_uint32 val);
extern void upmu_set_rg_vcn33_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcn33_en_wifi(kal_uint32 val);
extern void upmu_set_vcn33_on_ctrl_wifi(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn33_en(void);
extern void upmu_set_rg_vcn28_bist_en(kal_uint32 val);
extern void upmu_set_rg_vcn28_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vcn28_ocfb(kal_uint32 val);
extern void upmu_set_rg_vcn28_vosel(kal_uint32 val);
extern void upmu_set_rg_vcn28_cal(kal_uint32 val);
extern void upmu_set_rg_vcn28_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcn28_en(kal_uint32 val);
extern void upmu_set_vcn28_on_ctrl(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn28_en(void);
extern void upmu_set_vcn28_lp_sel(kal_uint32 val);
extern void upmu_set_vcn28_lp_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn28_mode(void);
extern kal_uint32 upmu_get_qi_vcn28_oc_status(void);
extern void upmu_set_vcn33_lp_sel(kal_uint32 val);
extern void upmu_set_vcn33_lp_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn33_mode(void);
extern void upmu_set_rg_vcn33_en(kal_uint32 val);
extern void upmu_set_rg_vcn33_bist_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn33_oc_status(void);
extern void upmu_set_vio28_lp_sel(kal_uint32 val);
extern void upmu_set_vio28_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vio28_mode(void);
extern void upmu_set_rg_vio28_stbtd(kal_uint32 val);
extern void upmu_set_vio28_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vio28_en(void);
extern void upmu_set_vusb_lp_sel(kal_uint32 val);
extern void upmu_set_vusb_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vusb_mode(void);
extern void upmu_set_rg_vusb_stbtd(kal_uint32 val);
extern void upmu_set_rg_vusb_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vusb_en(void);
extern void upmu_set_vmc_lp_sel(kal_uint32 val);
extern void upmu_set_vmc_lp_mode_set(kal_uint32 val);
extern void upmu_set_rg_stb_sel(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vmc_mode(void);
extern void upmu_set_rg_vmc_stbtd(kal_uint32 val);
extern void upmu_set_rg_vmc_en(kal_uint32 val);
extern void upmu_set_rg_vmc_int_dis_sel(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vmc_en(void);
extern void upmu_set_vmch_lp_sel(kal_uint32 val);
extern void upmu_set_vmch_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vmch_mode(void);
extern void upmu_set_rg_vmch_stbtd(kal_uint32 val);
extern void upmu_set_rg_vmch_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vmch_en(void);
extern void upmu_set_vemc_3v3_lp_sel(kal_uint32 val);
extern void upmu_set_vemc_3v3_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vemc_3v3_mode(void);
extern void upmu_set_rg_vemc_3v3_stbtd(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vemc_3v3_en(void);
extern void upmu_set_vgp1_lp_sel(kal_uint32 val);
extern void upmu_set_vgp1_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vgp1_mode(void);
extern void upmu_set_rg_vgp1_stbtd(kal_uint32 val);
extern void upmu_set_rg_vgp1_en(kal_uint32 val);
extern void upmu_set_vgp2_lp_sel(kal_uint32 val);
extern void upmu_set_vgp2_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vgp2_mode(void);
extern void upmu_set_rg_vgp2_stbtd(kal_uint32 val);
extern void upmu_set_rg_vgp2_en(kal_uint32 val);
extern void upmu_set_vgp3_lp_sel(kal_uint32 val);
extern void upmu_set_vgp3_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vgp3_mode(void);
extern void upmu_set_rg_vgp3_stbtd(kal_uint32 val);
extern void upmu_set_rg_vgp3_en(kal_uint32 val);
extern void upmu_set_rg_vcn_1v8_ndis_en(kal_uint32 val);
extern void upmu_set_vcn_1v8_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vcn_1v8_ocfb(kal_uint32 val);
extern void upmu_set_rg_vcn_1v8_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vcn_1v8_cal(kal_uint32 val);
extern void upmu_set_vcn_1v8_lp_sel(kal_uint32 val);
extern void upmu_set_vcn_1v8_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn_1v8_mode(void);
extern void upmu_set_rg_vcn_1v8_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcn_1v8_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcn_1v8_en(void);
extern void upmu_set_re_digldorsv1(kal_uint32 val);
extern void upmu_set_vsim1_lp_sel(kal_uint32 val);
extern void upmu_set_vsim1_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vsim1_mode(void);
extern void upmu_set_rg_vsim1_stbtd(kal_uint32 val);
extern void upmu_set_rg_vsim1_en(kal_uint32 val);
extern void upmu_set_vsim2_lp_sel(kal_uint32 val);
extern void upmu_set_vsim2_lp_mode_set(kal_uint32 val);
extern void upmu_set_vsim2_ther_shdn_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vsim2_mode(void);
extern void upmu_set_rg_vsim2_stbtd(kal_uint32 val);
extern void upmu_set_rg_vsim2_en(kal_uint32 val);
extern void upmu_set_rg_vrtc_force_on(kal_uint32 val);
extern void upmu_set_vrtc_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vrtc_en(void);
extern void upmu_set_rg_vemc_3v3_bist_en(kal_uint32 val);
extern void upmu_set_rg_vmch_bist_en(kal_uint32 val);
extern void upmu_set_rg_vmc_bist_en(kal_uint32 val);
extern void upmu_set_rg_vusb_bist_en(kal_uint32 val);
extern void upmu_set_rg_vio28_bist_en(kal_uint32 val);
extern void upmu_set_rg_vrtc_bist_en(kal_uint32 val);
extern void upmu_set_rg_vsim2_bist_en(kal_uint32 val);
extern void upmu_set_rg_vsim1_bist_en(kal_uint32 val);
extern void upmu_set_rg_vibr_bist_en(kal_uint32 val);
extern void upmu_set_rg_vgp3_bist_en(kal_uint32 val);
extern void upmu_set_rg_vgp2_bist_en(kal_uint32 val);
extern void upmu_set_rg_vgp1_bist_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vemc_3v3_oc_status(void);
extern kal_uint32 upmu_get_qi_vmch_oc_status(void);
extern kal_uint32 upmu_get_qi_vmc_oc_status(void);
extern kal_uint32 upmu_get_qi_vusb_oc_status(void);
extern kal_uint32 upmu_get_qi_vio28_oc_status(void);
extern kal_uint32 upmu_get_qi_vsim2_oc_status(void);
extern kal_uint32 upmu_get_qi_vsim1_oc_status(void);
extern kal_uint32 upmu_get_qi_vibr_oc_status(void);
extern kal_uint32 upmu_get_qi_vgp3_oc_status(void);
extern kal_uint32 upmu_get_qi_vgp2_oc_status(void);
extern kal_uint32 upmu_get_qi_vgp1_oc_status(void);
extern void upmu_set_re_digldorsv2(kal_uint32 val);
extern void upmu_set_rg_vio28_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vio28_ocfb(kal_uint32 val);
extern void upmu_set_rg_vio28_cal(kal_uint32 val);
extern void upmu_set_rg_vusb_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vusb_ocfb(kal_uint32 val);
extern void upmu_set_rg_vusb_cal(kal_uint32 val);
extern void upmu_set_rg_vmc_ndis_en(kal_uint32 val);
extern void upmu_set_vmc_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vmc_ocfb(kal_uint32 val);
extern void upmu_set_rg_vmc_vosel(kal_uint32 val);
extern void upmu_set_rg_vmc_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vmc_stb_sel_cal(kal_uint32 val);
extern void upmu_set_rg_vmc_cal(kal_uint32 val);
extern void upmu_set_rg_vmch_ndis_en(kal_uint32 val);
extern void upmu_set_vmch_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vmch_ocfb(kal_uint32 val);
extern void upmu_set_rg_vmch_db_en(kal_uint32 val);
extern void upmu_set_rg_vmch_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vmch_vosel(kal_uint32 val);
extern void upmu_set_rg_vmch_stb_sel_cal(kal_uint32 val);
extern void upmu_set_rg_vmch_cal(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_ndis_en(kal_uint32 val);
extern void upmu_set_vemc_3v3_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_ocfb(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_dl_en(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_db_en(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_vosel(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_stb_sel_cal(kal_uint32 val);
extern void upmu_set_rg_vemc_3v3_cal(kal_uint32 val);
extern void upmu_set_rg_vgp1_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vgp1_ocfb(kal_uint32 val);
extern void upmu_set_rg_vgp1_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vgp1_vosel(kal_uint32 val);
extern void upmu_set_rg_vgp1_cal(kal_uint32 val);
extern void upmu_set_rg_vgp2_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vgp2_ocfb(kal_uint32 val);
extern void upmu_set_rg_vgp2_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vgp2_vosel(kal_uint32 val);
extern void upmu_set_rg_vgp2_cal(kal_uint32 val);
extern void upmu_set_rg_vgp3_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vgp3_ocfb(kal_uint32 val);
extern void upmu_set_rg_vgp3_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vgp3_vosel(kal_uint32 val);
extern void upmu_set_rg_vgp3_cal(kal_uint32 val);
extern void upmu_set_vcam_af_lp_sel(kal_uint32 val);
extern void upmu_set_vcam_af_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcam_af_mode(void);
extern void upmu_set_rg_vcam_af_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcam_af_en(kal_uint32 val);
extern void upmu_set_rg_vcam_af_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vcam_af_ocfb(kal_uint32 val);
extern void upmu_set_vcam_af_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vcam_af_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vcam_af_vosel(kal_uint32 val);
extern void upmu_set_rg_vcam_af_cal(kal_uint32 val);
extern void upmu_set_re_digldorsv3(kal_uint32 val);
extern void upmu_set_rg_vsim1_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vsim1_ocfb(kal_uint32 val);
extern void upmu_set_rg_vsim1_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vsim1_vosel(kal_uint32 val);
extern void upmu_set_rg_vsim1_cal(kal_uint32 val);
extern void upmu_set_rg_vsim2_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vsim2_ocfb(kal_uint32 val);
extern void upmu_set_rg_vsim2_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vsim2_vosel(kal_uint32 val);
extern void upmu_set_rg_vsim2_cal(kal_uint32 val);
extern void upmu_set_rg_vsysldo_reserve(kal_uint32 val);
extern void upmu_set_vibr_lp_sel(kal_uint32 val);
extern void upmu_set_vibr_lp_mode_set(kal_uint32 val);
extern void upmu_set_vibr_ther_shen_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vibr_mode(void);
extern void upmu_set_rg_vibr_stbtd(kal_uint32 val);
extern void upmu_set_rg_vibr_en(kal_uint32 val);
extern void upmu_set_rg_vibr_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vibr_ocfb(kal_uint32 val);
extern void upmu_set_rg_vibr_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vibr_vosel(kal_uint32 val);
extern void upmu_set_rg_vibr_stb_sel_cal(kal_uint32 val);
extern void upmu_set_rg_vibr_cal(kal_uint32 val);
extern void upmu_set_digldo_rsv1(kal_uint32 val);
extern void upmu_set_digldo_rsv0(kal_uint32 val);
extern void upmu_set_rg_ldo_ft(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcam_io_oc_status(void);
extern kal_uint32 upmu_get_qi_vcamd_oc_status(void);
extern kal_uint32 upmu_get_qi_vcn_1v8_oc_status(void);
extern kal_uint32 upmu_get_qi_vio18_oc_status(void);
extern kal_uint32 upmu_get_qi_vrf18_oc_status(void);
extern kal_uint32 upmu_get_qi_vm_oc_status(void);
extern kal_uint32 upmu_get_qi_vcam_af_oc_status(void);
extern void upmu_set_rg_vcam_af_bist_en(kal_uint32 val);
extern void upmu_set_rg_vcamd_io_bist_en(kal_uint32 val);
extern void upmu_set_rg_vcn_1v8_bist_en(kal_uint32 val);
extern void upmu_set_rg_vcamd_bist_en(kal_uint32 val);
extern void upmu_set_rg_vio18_bist_en(kal_uint32 val);
extern void upmu_set_rg_vm_bist_en(kal_uint32 val);
extern void upmu_set_rg_vrf18_bist_en(kal_uint32 val);
extern void upmu_set_vibr_on_ctrl(kal_uint32 val);
extern void upmu_set_vsim2_on_ctrl(kal_uint32 val);
extern void upmu_set_vsim1_on_ctrl(kal_uint32 val);
extern void upmu_set_vgp3_on_ctrl(kal_uint32 val);
extern void upmu_set_vgp2_on_ctrl(kal_uint32 val);
extern void upmu_set_vgp1_on_ctrl(kal_uint32 val);
extern void upmu_set_vrf18_lp_sel(kal_uint32 val);
extern void upmu_set_vrf18_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vrf18_mode(void);
extern void upmu_set_rg_vrf18_stbtd(kal_uint32 val);
extern void upmu_set_rg_vrf18_en(kal_uint32 val);
extern void upmu_set_rg_vrf18_ndis_en(kal_uint32 val);
extern void upmu_set_vrf18_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vrf18_ocfb(kal_uint32 val);
extern void upmu_set_rg_vrf18_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vrf18_cal(kal_uint32 val);
extern void upmu_set_vm_lp_sel(kal_uint32 val);
extern void upmu_set_vm_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vm_mode(void);
extern void upmu_set_rg_vm_stbtd(kal_uint32 val);
extern void upmu_set_rg_vm_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vm_en(void);
extern void upmu_set_rg_vm_ndis_en(kal_uint32 val);
extern void upmu_set_rg_vm_plcur_en(kal_uint32 val);
extern void upmu_set_rg_vm_plcur_cal(kal_uint32 val);
extern void upmu_set_rg_vm_vosel(kal_uint32 val);
extern void upmu_set_rg_vm_ocfb(kal_uint32 val);
extern void upmu_set_rg_vm_cal(kal_uint32 val);
extern void upmu_set_vio18_lp_sel(kal_uint32 val);
extern void upmu_set_vio18_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vio18_mode(void);
extern void upmu_set_rg_vio18_stbtd(kal_uint32 val);
extern void upmu_set_rg_vio18_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vio18_en(void);
extern void upmu_set_rg_vio18_ndis_en(kal_uint32 val);
extern void upmu_set_vio18_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vio18_ocfb(kal_uint32 val);
extern void upmu_set_rg_vio18_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vio18_cal(kal_uint32 val);
extern void upmu_set_vcamd_lp_sel(kal_uint32 val);
extern void upmu_set_vcamd_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcamd_mode(void);
extern void upmu_set_rg_vcamd_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcamd_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcamd_en(void);
extern void upmu_set_rg_vcamd_ndis_en(kal_uint32 val);
extern void upmu_set_vcamd_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vcamd_ocfb(kal_uint32 val);
extern void upmu_set_rg_vcamd_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vcamd_vosel(kal_uint32 val);
extern void upmu_set_rg_vcamd_cal(kal_uint32 val);
extern void upmu_set_vcam_io_lp_sel(kal_uint32 val);
extern void upmu_set_vcam_io_lp_mode_set(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcam_io_mode(void);
extern void upmu_set_rg_vcam_io_stbtd(kal_uint32 val);
extern void upmu_set_rg_vcam_io_en(kal_uint32 val);
extern kal_uint32 upmu_get_qi_vcam_io_en(void);
extern void upmu_set_rg_vcam_io_ndis_en(kal_uint32 val);
extern void upmu_set_vcam_io_on_ctrl(kal_uint32 val);
extern void upmu_set_rg_vcam_io_ocfb(kal_uint32 val);
extern void upmu_set_rg_vcam_io_stb_sel(kal_uint32 val);
extern void upmu_set_rg_vcam_io_cal(kal_uint32 val);
extern void upmu_set_rg_efuse_addr(kal_uint32 val);
extern void upmu_set_rg_efuse_prog(kal_uint32 val);
extern void upmu_set_rg_efuse_en(kal_uint32 val);
extern void upmu_set_rg_efuse_pkey(kal_uint32 val);
extern void upmu_set_rg_efuse_rd_trig(kal_uint32 val);
extern void upmu_set_rg_efuse_prog_src(kal_uint32 val);
extern void upmu_set_rg_skip_efuse_out(kal_uint32 val);
extern void upmu_set_rg_rd_rdy_bypass(kal_uint32 val);
extern kal_uint32 upmu_get_rg_efuse_rd_ack(void);
extern kal_uint32 upmu_get_rg_efuse_busy(void);
extern void upmu_set_rg_efuse_val_0_15(kal_uint32 val);
extern void upmu_set_rg_efuse_val_16_31(kal_uint32 val);
extern void upmu_set_rg_efuse_val_32_47(kal_uint32 val);
extern void upmu_set_rg_efuse_val_48_63(kal_uint32 val);
extern void upmu_set_rg_efuse_val_64_79(kal_uint32 val);
extern void upmu_set_rg_efuse_val_80_95(kal_uint32 val);
extern void upmu_set_rg_efuse_val_96_111(kal_uint32 val);
extern void upmu_set_rg_efuse_val_112_127(kal_uint32 val);
extern void upmu_set_rg_efuse_val_128_143(kal_uint32 val);
extern void upmu_set_rg_efuse_val_144_159(kal_uint32 val);
extern void upmu_set_rg_efuse_val_160_175(kal_uint32 val);
extern void upmu_set_rg_efuse_val_176_191(kal_uint32 val);
extern kal_uint32 upmu_get_rg_efuse_dout_0_15(void);
extern kal_uint32 upmu_get_rg_efuse_dout_16_31(void);
extern kal_uint32 upmu_get_rg_efuse_dout_32_47(void);
extern kal_uint32 upmu_get_rg_efuse_dout_48_63(void);
extern kal_uint32 upmu_get_rg_efuse_dout_64_79(void);
extern kal_uint32 upmu_get_rg_efuse_dout_80_95(void);
extern kal_uint32 upmu_get_rg_efuse_dout_96_111(void);
extern kal_uint32 upmu_get_rg_efuse_dout_112_127(void);
extern kal_uint32 upmu_get_rg_efuse_dout_128_143(void);
extern kal_uint32 upmu_get_rg_efuse_dout_144_159(void);
extern kal_uint32 upmu_get_rg_efuse_dout_160_175(void);
extern kal_uint32 upmu_get_rg_efuse_dout_176_191(void);
extern void upmu_set_rg_otp_pa(kal_uint32 val);
extern void upmu_set_rg_otp_pdin(kal_uint32 val);
extern void upmu_set_rg_otp_ptm(kal_uint32 val);
extern void upmu_set_mix_eosc32_opt(kal_uint32 val);
extern kal_uint32 upmu_get_mix_xosc32_stp_cpdtb(void);
extern void upmu_set_mix_xosc32_stp_pwdb(kal_uint32 val);
extern kal_uint32 upmu_get_mix_xosc32_stp_lpdtb(void);
extern void upmu_set_mix_xosc32_stp_lpden(kal_uint32 val);
extern void upmu_set_mix_xosc32_stp_lpdrst(kal_uint32 val);
extern void upmu_set_mix_xosc32_stp_cali(kal_uint32 val);
extern void upmu_set_stmp_mode(kal_uint32 val);
extern void upmu_set_mix_eosc32_stp_chop_en(kal_uint32 val);
extern void upmu_set_mix_dcxo_stp_lvsh_en(kal_uint32 val);
extern void upmu_set_mix_pmu_stp_ddlo_vrtc(kal_uint32 val);
extern void upmu_set_mix_pmu_stp_ddlo_vrtc_en(kal_uint32 val);
extern void upmu_set_mix_rtc_stp_xosc32_enb(kal_uint32 val);
extern void upmu_set_mix_dcxo_stp_test_deglitch_mode(kal_uint32 val);
extern void upmu_set_mix_eosc32_stp_rsv(kal_uint32 val);
extern void upmu_set_mix_eosc32_vct_en(kal_uint32 val);
extern void upmu_set_mix_stp_bbwakeup(kal_uint32 val);
extern kal_uint32 upmu_get_mix_stp_rtc_ddlo(void);
extern kal_uint32 upmu_get_mix_rtc_xosc32_enb(void);
extern void upmu_set_mix_efuse_xosc32_enb_opt(kal_uint32 val);
extern void upmu_set_rg_audull_vcfg(kal_uint32 val);
extern void upmu_set_rg_audull_vupg(kal_uint32 val);
extern void upmu_set_rg_audull_vpwdb_pga(kal_uint32 val);
extern void upmu_set_rg_audull_vpwdb_adc(kal_uint32 val);
extern void upmu_set_rg_audull_vadc_denb(kal_uint32 val);
extern void upmu_set_rg_audull_vadc_dvref_cal(kal_uint32 val);
extern void upmu_set_rg_audull_vref24_en(kal_uint32 val);
extern void upmu_set_rg_audull_vcm14_en(kal_uint32 val);
extern void upmu_set_rg_audull_vcmsel(kal_uint32 val);
extern void upmu_set_rg_audull_chs_en(kal_uint32 val);
extern void upmu_set_rg_audull_vcali(kal_uint32 val);
extern void upmu_set_rg_audulr_vcfg(kal_uint32 val);
extern void upmu_set_rg_audulr_vupg(kal_uint32 val);
extern void upmu_set_rg_audulr_vpwdb_pga(kal_uint32 val);
extern void upmu_set_rg_audulr_vpwdb_adc(kal_uint32 val);
extern void upmu_set_rg_audulr_vadc_denb(kal_uint32 val);
extern void upmu_set_rg_audulr_vadc_dvref_cal(kal_uint32 val);
extern void upmu_set_rg_audulr_vref24_en(kal_uint32 val);
extern void upmu_set_rg_audulr_vcm14_en(kal_uint32 val);
extern void upmu_set_rg_audulr_vcmsel(kal_uint32 val);
extern void upmu_set_rg_audulr_chs_en(kal_uint32 val);
extern void upmu_set_rg_audulr_vcali(kal_uint32 val);
extern void upmu_set_rg_aud_igbias_cali(kal_uint32 val);
extern void upmu_set_rg_aud_rsv(kal_uint32 val);
extern void upmu_set_rg_amuter(kal_uint32 val);
extern void upmu_set_rg_amutel(kal_uint32 val);
extern void upmu_set_rg_adacl_pwdb(kal_uint32 val);
extern void upmu_set_rg_adacr_pwdb(kal_uint32 val);
extern void upmu_set_rg_abias_pwdb(kal_uint32 val);
extern void upmu_set_rg_aoutl_pwdb(kal_uint32 val);
extern void upmu_set_rg_aoutr_pwdb(kal_uint32 val);
extern void upmu_set_rg_acali(kal_uint32 val);
extern void upmu_set_rg_apgr(kal_uint32 val);
extern void upmu_set_rg_apgl(kal_uint32 val);
extern void upmu_set_rg_abuf_bias(kal_uint32 val);
extern void upmu_set_rg_abuf_inshort(kal_uint32 val);
extern void upmu_set_rg_ahfmode(kal_uint32 val);
extern void upmu_set_rg_adacck_en(kal_uint32 val);
extern void upmu_set_rg_dacref(kal_uint32 val);
extern void upmu_set_rg_adepopx_en(kal_uint32 val);
extern void upmu_set_rg_adepopx(kal_uint32 val);
extern void upmu_set_rg_depop_vcm_en(kal_uint32 val);
extern void upmu_set_rg_depop_vcmsel(kal_uint32 val);
extern void upmu_set_rg_depop_cursel(kal_uint32 val);
extern void upmu_set_rg_chargeoption_depop(kal_uint32 val);
extern void upmu_set_rg_avcmgen_en(kal_uint32 val);
extern void upmu_set_rg_auddl_vref24_en(kal_uint32 val);
extern void upmu_set_rg_abirsv(kal_uint32 val);
extern void upmu_set_rg_vbuf_float(kal_uint32 val);
extern void upmu_set_rg_vdpg(kal_uint32 val);
extern void upmu_set_rg_vbuf_pwdb(kal_uint32 val);
extern void upmu_set_rg_vbuf_bias(kal_uint32 val);
extern void upmu_set_rg_vdepop(kal_uint32 val);
extern void upmu_set_rg_v2spk(kal_uint32 val);
extern void upmu_set_rg_hsoutstbenh(kal_uint32 val);
extern void upmu_set_audtop_con8_rsv_0(kal_uint32 val);
extern void upmu_set_rg_clksq_monen(kal_uint32 val);
extern void upmu_set_rg_auddigmicen(kal_uint32 val);
extern void upmu_set_rg_audpwdbmicbias(kal_uint32 val);
extern void upmu_set_rg_auddigmicpduty(kal_uint32 val);
extern void upmu_set_rg_auddigmicnduty(kal_uint32 val);
extern void upmu_set_rg_auddigmicbias(kal_uint32 val);
extern void upmu_set_rg_audmicbiasvref(kal_uint32 val);
extern void upmu_set_rg_audsparevmic(kal_uint32 val);
extern void upmu_set_rg_vbirx_zcd_en(kal_uint32 val);
extern void upmu_set_rg_vbirx_zcd_cali(kal_uint32 val);
extern void upmu_set_rg_vbirx_zcd_hys_enb(kal_uint32 val);
extern kal_uint32 upmu_get_rg_vbirx_zcd_status(void);
extern kal_uint32 upmu_get_rg_adc_out_batsns(void);
extern kal_uint32 upmu_get_rg_adc_rdy_batsns(void);
extern kal_uint32 upmu_get_rg_adc_out_isense(void);
extern kal_uint32 upmu_get_rg_adc_rdy_isense(void);
extern kal_uint32 upmu_get_rg_adc_out_vcdt(void);
extern kal_uint32 upmu_get_rg_adc_rdy_vcdt(void);
extern kal_uint32 upmu_get_rg_adc_out_baton1(void);
extern kal_uint32 upmu_get_rg_adc_rdy_baton1(void);
extern kal_uint32 upmu_get_rg_adc_out_thr_sense1(void);
extern kal_uint32 upmu_get_rg_adc_rdy_thr_sense1(void);
extern kal_uint32 upmu_get_rg_adc_out_thr_sense2(void);
extern kal_uint32 upmu_get_rg_adc_rdy_thr_sense2(void);
extern kal_uint32 upmu_get_rg_adc_out_baton2(void);
extern kal_uint32 upmu_get_rg_adc_rdy_baton2(void);
extern kal_uint32 upmu_get_rg_adc_out_ch5(void);
extern kal_uint32 upmu_get_rg_adc_rdy_ch5(void);
extern kal_uint32 upmu_get_rg_adc_out_wakeup_pchr(void);
extern kal_uint32 upmu_get_rg_adc_rdy_wakeup_pchr(void);
extern kal_uint32 upmu_get_rg_adc_out_wakeup_swchr(void);
extern kal_uint32 upmu_get_rg_adc_rdy_wakeup_swchr(void);
extern kal_uint32 upmu_get_rg_adc_out_lbat(void);
extern kal_uint32 upmu_get_rg_adc_rdy_lbat(void);
extern kal_uint32 upmu_get_rg_adc_out_ch6(void);
extern kal_uint32 upmu_get_rg_adc_rdy_ch6(void);
extern kal_uint32 upmu_get_rg_adc_rdy_gps(void);
extern kal_uint32 upmu_get_rg_adc_out_gps(void);
extern kal_uint32 upmu_get_rg_adc_out_gps_lsb(void);
extern kal_uint32 upmu_get_rg_adc_out_md(void);
extern kal_uint32 upmu_get_rg_adc_out_md_lsb(void);
extern kal_uint32 upmu_get_rg_adc_rdy_md(void);
extern kal_uint32 upmu_get_rg_adc_out_int(void);
extern kal_uint32 upmu_get_rg_adc_rdy_int(void);
extern kal_uint32 upmu_get_rg_adc_out_rsv1(void);
extern kal_uint32 upmu_get_rg_adc_out_rsv2(void);
extern kal_uint32 upmu_get_rg_adc_out_rsv3(void);
extern void upmu_set_rg_sw_gain_trim(kal_uint32 val);
extern void upmu_set_rg_sw_offset_trim(kal_uint32 val);
extern void upmu_set_rg_adc_pwdb(kal_uint32 val);
extern void upmu_set_rg_adc_pwdb_swctrl(kal_uint32 val);
extern void upmu_set_rg_adc_cali_rate(kal_uint32 val);
extern void upmu_set_rg_adc_cali_en(kal_uint32 val);
extern void upmu_set_rg_adc_cali_force(kal_uint32 val);
extern void upmu_set_rg_adc_autorst_range(kal_uint32 val);
extern void upmu_set_rg_adc_autorst_en(kal_uint32 val);
extern void upmu_set_rg_adc_latch_edge(kal_uint32 val);
extern void upmu_set_rg_adc_filter_order(kal_uint32 val);
extern void upmu_set_rg_adc_swctrl_en(kal_uint32 val);
extern void upmu_set_rg_adcin_vsen_en(kal_uint32 val);
extern void upmu_set_rg_adcin_vsen_mux_en(kal_uint32 val);
extern void upmu_set_rg_adcin_vbat_en(kal_uint32 val);
extern void upmu_set_rg_adcin_chr_en(kal_uint32 val);
extern void upmu_set_rg_auxadc_chsel(kal_uint32 val);
extern void upmu_set_rg_lbat_debt_max(kal_uint32 val);
extern void upmu_set_rg_lbat_debt_min(kal_uint32 val);
extern void upmu_set_rg_lbat_det_prd_15_0(kal_uint32 val);
extern void upmu_set_rg_lbat_det_prd_19_16(kal_uint32 val);
extern void upmu_set_rg_lbat_volt_max(kal_uint32 val);
extern void upmu_set_rg_lbat_irq_en_max(kal_uint32 val);
extern void upmu_set_rg_lbat_en_max(kal_uint32 val);
extern kal_uint32 upmu_get_rg_lbat_max_irq_b(void);
extern void upmu_set_rg_lbat_volt_min(kal_uint32 val);
extern void upmu_set_rg_lbat_irq_en_min(kal_uint32 val);
extern void upmu_set_rg_lbat_en_min(kal_uint32 val);
extern kal_uint32 upmu_get_rg_lbat_min_irq_b(void);
extern kal_uint32 upmu_get_rg_lbat_debounce_count_max(void);
extern kal_uint32 upmu_get_rg_lbat_debounce_count_min(void);
extern void upmu_set_rg_data_reuse_sel(kal_uint32 val);
extern void upmu_set_rg_auxadc_bist_enb(kal_uint32 val);
extern void upmu_set_rg_osr(kal_uint32 val);
extern void upmu_set_rg_osr_gps(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch7_sel(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch6_sel(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch5_sel(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch4_sel(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch3_sel(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch2_sel(kal_uint32 val);
extern void upmu_set_rg_adc_trim_ch0_sel(kal_uint32 val);
extern void upmu_set_rg_vbuf_calen(kal_uint32 val);
extern void upmu_set_rg_vbuf_exten(kal_uint32 val);
extern void upmu_set_rg_vbuf_byp(kal_uint32 val);
extern void upmu_set_rg_vbuf_en(kal_uint32 val);
extern void upmu_set_rg_source_lbat_sel(kal_uint32 val);
extern void upmu_set_efuse_gain_ch0_trim(kal_uint32 val);
extern void upmu_set_efuse_offset_ch0_trim(kal_uint32 val);
extern void upmu_set_efuse_gain_ch4_trim(kal_uint32 val);
extern void upmu_set_efuse_offset_ch4_trim(kal_uint32 val);
extern void upmu_set_efuse_gain_ch7_trim(kal_uint32 val);
extern void upmu_set_efuse_offset_ch7_trim(kal_uint32 val);
extern void upmu_set_rg_adc_ibias(kal_uint32 val);
extern void upmu_set_rg_adc_rst(kal_uint32 val);
extern void upmu_set_rg_adc_lp_en(kal_uint32 val);
extern void upmu_set_rg_adc_input_short(kal_uint32 val);
extern void upmu_set_rg_adc_chopper_en(kal_uint32 val);
extern void upmu_set_rg_vpwdb_adc(kal_uint32 val);
extern void upmu_set_rg_vref18_en(kal_uint32 val);
extern void upmu_set_rg_adc_chs_sel(kal_uint32 val);
extern void upmu_set_rg_adc_dvref_cal(kal_uint32 val);
extern void upmu_set_rg_adc_denb(kal_uint32 val);
extern void upmu_set_rg_adc_sleep_mode_en(kal_uint32 val);
extern void upmu_set_rg_adc_gps_status(kal_uint32 val);
extern void upmu_set_rg_adc_md_status(kal_uint32 val);
extern void upmu_set_rg_adc_test_mode_en(kal_uint32 val);
extern void upmu_set_rg_adc_test_out_sel(kal_uint32 val);
extern void upmu_set_rg_deci_bypass_en(kal_uint32 val);
extern void upmu_set_rg_adc_clk_aon(kal_uint32 val);
extern void upmu_set_rg_adc_deci_force(kal_uint32 val);
extern void upmu_set_rg_adc_deci_gdly(kal_uint32 val);
extern void upmu_set_rg_md_rqst(kal_uint32 val);
extern void upmu_set_rg_gps_rqst(kal_uint32 val);
extern void upmu_set_rg_ap_rqst_list(kal_uint32 val);
extern void upmu_set_rg_ap_rqst(kal_uint32 val);
extern void upmu_set_rg_ap_rqst_list_rsv(kal_uint32 val);
extern void upmu_set_rg_adc_out_trim_enb(kal_uint32 val);
extern void upmu_set_rg_adc_trim_comp(kal_uint32 val);
extern void upmu_set_rg_adc_2s_comp_enb(kal_uint32 val);
extern void upmu_set_rg_cic_out_raw(kal_uint32 val);
extern void upmu_set_rg_data_skip_enb(kal_uint32 val);
extern void upmu_set_rg_data_skip_num(kal_uint32 val);
extern void upmu_set_rg_adc_rev(kal_uint32 val);
extern void upmu_set_rg_adc_rsv1(kal_uint32 val);
extern void upmu_set_rg_adc_rsv2(kal_uint32 val);
extern void upmu_set_rg_audaccdetvthcal(kal_uint32 val);
extern void upmu_set_rg_audaccdetswctrl(kal_uint32 val);
extern void upmu_set_rg_audaccdettvdet(kal_uint32 val);
extern void upmu_set_rg_audaccdetvin1pulllow(kal_uint32 val);
extern void upmu_set_audaccdetauxadcswctrl(kal_uint32 val);
extern void upmu_set_audaccdetauxadcswctrl_sel(kal_uint32 val);
extern void upmu_set_rg_audaccdetrsv(kal_uint32 val);
extern void upmu_set_accdet_en(kal_uint32 val);
extern void upmu_set_accdet_seq_init(kal_uint32 val);
extern void upmu_set_accdet_cmp_pwm_en(kal_uint32 val);
extern void upmu_set_accdet_vth_pwm_en(kal_uint32 val);
extern void upmu_set_accdet_mbias_pwm_en(kal_uint32 val);
extern void upmu_set_accdet_cmp_pwm_idle(kal_uint32 val);
extern void upmu_set_accdet_vth_pwm_idle(kal_uint32 val);
extern void upmu_set_accdet_mbias_pwm_idle(kal_uint32 val);
extern void upmu_set_accdet_pwm_width(kal_uint32 val);
extern void upmu_set_accdet_pwm_thresh(kal_uint32 val);
extern void upmu_set_accdet_rise_delay(kal_uint32 val);
extern void upmu_set_accdet_fall_delay(kal_uint32 val);
extern void upmu_set_accdet_debounce0(kal_uint32 val);
extern void upmu_set_accdet_debounce1(kal_uint32 val);
extern void upmu_set_accdet_debounce2(kal_uint32 val);
extern void upmu_set_accdet_debounce3(kal_uint32 val);
extern void upmu_set_accdet_ival_cur_in(kal_uint32 val);
extern void upmu_set_accdet_ival_sam_in(kal_uint32 val);
extern void upmu_set_accdet_ival_mem_in(kal_uint32 val);
extern void upmu_set_accdet_ival_sel(kal_uint32 val);
extern kal_uint32 upmu_get_accdet_irq(void);
extern void upmu_set_accdet_irq_clr(kal_uint32 val);
extern void upmu_set_accdet_test_mode0(kal_uint32 val);
extern void upmu_set_accdet_test_mode1(kal_uint32 val);
extern void upmu_set_accdet_test_mode2(kal_uint32 val);
extern void upmu_set_accdet_test_mode3(kal_uint32 val);
extern void upmu_set_accdet_test_mode4(kal_uint32 val);
extern void upmu_set_accdet_test_mode5(kal_uint32 val);
extern void upmu_set_accdet_pwm_sel(kal_uint32 val);
extern void upmu_set_accdet_in_sw(kal_uint32 val);
extern void upmu_set_accdet_cmp_en_sw(kal_uint32 val);
extern void upmu_set_accdet_vth_en_sw(kal_uint32 val);
extern void upmu_set_accdet_mbias_en_sw(kal_uint32 val);
extern void upmu_set_accdet_pwm_en_sw(kal_uint32 val);
extern kal_uint32 upmu_get_accdet_in(void);
extern kal_uint32 upmu_get_accdet_cur_in(void);
extern kal_uint32 upmu_get_accdet_sam_in(void);
extern kal_uint32 upmu_get_accdet_mem_in(void);
extern kal_uint32 upmu_get_accdet_state(void);
extern kal_uint32 upmu_get_accdet_mbias_clk(void);
extern kal_uint32 upmu_get_accdet_vth_clk(void);
extern kal_uint32 upmu_get_accdet_cmp_clk(void);
extern kal_uint32 upmu_get_da_audaccdetauxadcswctrl(void);
extern kal_uint32 upmu_get_accdet_cur_deb(void);
extern void upmu_set_accdet_rsv_con0(kal_uint32 val);
extern void upmu_set_accdet_rsv_con1(kal_uint32 val);
