#ifndef _MT_SPM_
#define _MT_SPM_

#include <typedefs.h>
#include <mt6582.h>
#include <sync_write.h>

/*
 * for SPM register control
 */
#define SPM_POWERON_CONFIG_SET      (SPM_BASE + 0x0000)
#define SPM_POWER_ON_VAL0           (SPM_BASE + 0x0010)
#define SPM_POWER_ON_VAL1           (SPM_BASE + 0x0014)
#define SPM_CLK_SETTLE              (SPM_BASE + 0x0100)
#define SPM_FC0_PWR_CON             (SPM_BASE + 0x0200)
#define SPM_CPU_PWR_CON             (SPM_BASE + 0x0208)
#define SPM_VDE_PWR_CON             (SPM_BASE + 0x0210)
#define SPM_MFG_PWR_CON             (SPM_BASE + 0x0214)
#define SPM_FC1_PWR_CON             (SPM_BASE + 0x0218)
#define SPM_FC2_PWR_CON             (SPM_BASE + 0x021c)
#define SPM_FC3_PWR_CON             (SPM_BASE + 0x0220)
#define SPM_IFR_PWR_CON             (SPM_BASE + 0x0234)
#define SPM_ISP_PWR_CON             (SPM_BASE + 0x0238)
#define SPM_DIS_PWR_CON             (SPM_BASE + 0x023c)
#define SPM_DPY_PWR_CON             (SPM_BASE + 0x0240)
#define SPM_CPU_L2_DAT_PDN          (SPM_BASE + 0x0244)
#define SPM_CPU_L2_DAT_SLEEP_B      (SPM_BASE + 0x0248)
#define SPM_MP_CORE0_AUX            (SPM_BASE + 0x024c)
#define SPM_MP_CORE1_AUX            (SPM_BASE + 0x0250)
#define SPM_MP_CORE2_AUX            (SPM_BASE + 0x0254)
#define SPM_MP_CORE3_AUX            (SPM_BASE + 0x0258)
#define SPM_CPU_FC0_L1_PDN          (SPM_BASE + 0x025c)
#define SPM_CPU_FC1_L1_PDN          (SPM_BASE + 0x0264)
#define SPM_CPU_FC2_L1_PDN          (SPM_BASE + 0x026c)
#define SPM_CPU_FC3_L1_PDN          (SPM_BASE + 0x0274)
#define SPM_IFR_FH_SRAM_CTRL        (SPM_BASE + 0x027c)
#define SPM_CONN_PWR_CON            (SPM_BASE + 0x0280)
#define SPM_MD_PWR_CON              (SPM_BASE + 0x0284)
#define SPM_MCU_PWR_CON             (SPM_BASE + 0x0290)
#define SPM_IFR_SRAMROM_CON         (SPM_BASE + 0x0294)
#define SPM_PCM_CON0                (SPM_BASE + 0x0310)
#define SPM_PCM_CON1                (SPM_BASE + 0x0314)
#define SPM_PCM_IM_PTR              (SPM_BASE + 0x0318)
#define SPM_PCM_IM_LEN              (SPM_BASE + 0x031c)
#define SPM_PCM_REG_DATA_INI        (SPM_BASE + 0x0320)
#define SPM_PCM_EVENT_VECTOR0       (SPM_BASE + 0x0340)
#define SPM_PCM_EVENT_VECTOR1       (SPM_BASE + 0x0344)
#define SPM_PCM_EVENT_VECTOR2       (SPM_BASE + 0x0348)
#define SPM_PCM_EVENT_VECTOR3       (SPM_BASE + 0x034c)
#define SPM_PCM_MAS_PAUSE_MASK      (SPM_BASE + 0x0354)
#define SPM_PCM_PWR_IO_EN           (SPM_BASE + 0x0358)
#define SPM_PCM_TIMER_VAL           (SPM_BASE + 0x035c)
#define SPM_PCM_TIMER_OUT           (SPM_BASE + 0x0360)
#define SPM_PCM_REG0_DATA           (SPM_BASE + 0x0380)
#define SPM_PCM_REG1_DATA           (SPM_BASE + 0x0384)
#define SPM_PCM_REG2_DATA           (SPM_BASE + 0x0388)
#define SPM_PCM_REG3_DATA           (SPM_BASE + 0x038c)
#define SPM_PCM_REG4_DATA           (SPM_BASE + 0x0390)
#define SPM_PCM_REG5_DATA           (SPM_BASE + 0x0394)
#define SPM_PCM_REG6_DATA           (SPM_BASE + 0x0398)
#define SPM_PCM_REG7_DATA           (SPM_BASE + 0x039c)
#define SPM_PCM_REG8_DATA           (SPM_BASE + 0x03a0)
#define SPM_PCM_REG9_DATA           (SPM_BASE + 0x03a4)
#define SPM_PCM_REG10_DATA          (SPM_BASE + 0x03a8)
#define SPM_PCM_REG11_DATA          (SPM_BASE + 0x03ac)
#define SPM_PCM_REG12_DATA          (SPM_BASE + 0x03b0)
#define SPM_PCM_REG13_DATA          (SPM_BASE + 0x03b4)
#define SPM_PCM_REG14_DATA          (SPM_BASE + 0x03b8)
#define SPM_PCM_REG15_DATA          (SPM_BASE + 0x03bc)
#define SPM_PCM_EVENT_REG_STA       (SPM_BASE + 0x03c0)
#define SPM_PCM_FSM_STA             (SPM_BASE + 0x03c4)
#define SPM_PCM_IM_HOST_RW_PTR      (SPM_BASE + 0x03c8)
#define SPM_PCM_IM_HOST_RW_DAT      (SPM_BASE + 0x03cc)
#define SPM_PCM_EVENT_VECTOR4       (SPM_BASE + 0x03d0)
#define SPM_PCM_EVENT_VECTOR5       (SPM_BASE + 0x03d4)
#define SPM_PCM_EVENT_VECTOR6       (SPM_BASE + 0x03d8)
#define SPM_PCM_EVENT_VECTOR7       (SPM_BASE + 0x03dc)
#define SPM_PCM_SW_INT_SEL          (SPM_BASE + 0x03e0)
#define SPM_PCM_SW_INT_CLEAR        (SPM_BASE + 0x03e4)
#define SPM_CLK_CON                 (SPM_BASE + 0x0400)
#define SPM_APMCU_PWRCTL            (SPM_BASE + 0x0600)
#define SPM_AP_DVFS_CON_SET         (SPM_BASE + 0x0604)
#define SPM_AP_STANBY_CON           (SPM_BASE + 0x0608)
#define SPM_PWR_STATUS              (SPM_BASE + 0x060c)
#define SPM_PWR_STATUS_S            (SPM_BASE + 0x0610)
#define SPM_SLEEP_TIMER_STA         (SPM_BASE + 0x0720)
#define SPM_SLEEP_TWAM_CON          (SPM_BASE + 0x0760)
#define SPM_SLEEP_TWAM_STATUS0      (SPM_BASE + 0x0764)
#define SPM_SLEEP_TWAM_STATUS1      (SPM_BASE + 0x0768)
#define SPM_SLEEP_TWAM_STATUS2      (SPM_BASE + 0x076c)
#define SPM_SLEEP_TWAM_STATUS3      (SPM_BASE + 0x0770)
#define SPM_SLEEP_WAKEUP_EVENT_MASK (SPM_BASE + 0x0810)
#define SPM_SLEEP_CPU_WAKEUP_EVENT  (SPM_BASE + 0x0814)
#define SPM_PCM_WDT_TIMER_VAL       (SPM_BASE + 0x0824)
#define SPM_SLEEP_ISR_MASK          (SPM_BASE + 0x0900)
#define SPM_SLEEP_ISR_STATUS        (SPM_BASE + 0x0904)
#define SPM_SLEEP_ISR_RAW_STA       (SPM_BASE + 0x0910)
#define SPM_PCM_RESERVE             (SPM_BASE + 0x0b00)
#define SPM_PCM_SRC_REQ             (SPM_BASE + 0x0b04)
#define SPM_SLEEP_CPU_IRQ_MASK      (SPM_BASE + 0x0b10)
#define SPM_PCM_DEBUG_CON           (SPM_BASE + 0x0b20)
#define SPM_CORE0_WFI_SEL           (SPM_BASE + 0x0f00)
#define SPM_CORE1_WFI_SEL           (SPM_BASE + 0x0f04)
#define SPM_CORE2_WFI_SEL           (SPM_BASE + 0x0f08)
#define SPM_CORE3_WFI_SEL           (SPM_BASE + 0x0f0c)

#define SPM_PROJECT_CODE            0xb16

#define CON0_PCM_KICK               (1U << 0)
#define CON0_IM_KICK                (1U << 1)
#define CON0_IM_SLEEP_DVS           (1U << 3)
#define CON0_EVENT_VEC0_EN          (1U << 4)
#define CON0_EVENT_VEC1_EN          (1U << 5)
#define CON0_EVENT_VEC2_EN          (1U << 6)
#define CON0_EVENT_VEC3_EN          (1U << 7)
#define CON0_EVENT_VEC4_EN          (1U << 8)
#define CON0_EVENT_VEC5_EN          (1U << 9)
#define CON0_EVENT_VEC6_EN          (1U << 10)
#define CON0_EVENT_VEC7_EN          (1U << 11)
#define CON0_PCM_SW_RESET           (1U << 15)
#define CON0_CFG_KEY                (SPM_PROJECT_CODE << 16)

#define CON1_IM_SLAVE               (1U << 0)
#define CON1_MIF_APBEN              (1U << 3)
#define CON1_PCM_TIMER_EN           (1U << 5)
#define CON1_IM_NONRP_EN            (1U << 6)
#define CON1_PCM_WDT_EN             (1U << 8)
#define CON1_PCM_WDT_WAKE_MODE      (1U << 9)
#define CON1_SPM_SRAM_SLP_B         (1U << 10)
#define CON1_SPM_SRAM_ISO_B         (1U << 11)
#define CON1_CFG_KEY                (SPM_PROJECT_CODE << 16)

#define PCM_PWRIO_EN_R0             (1U << 0)
#define PCM_PWRIO_EN_R7             (1U << 7)
#define PCM_RF_SYNC_R0              (1U << 16)
#define PCM_RF_SYNC_R7              (1U << 23)

#define R7_UART_CLK_OFF_REQ         (1U << 0)
#define R7_WDT_KICK_P               (1U << 22)

#define R13_CONN_SRCCLKENI          (1U << 1)
#define R13_MD_SRCCLKENI            (1U << 4)
#define R13_UART_CLK_OFF_ACK        (1U << 20)

#define CC_SYSCLK0_EN_0             (1U << 0)
#define CC_SYSCLK0_EN_1             (1U << 1)
#define CC_SYSSETTLE_SEL            (1U << 4)
#define CC_LOCK_INFRA_DCM           (1U << 5)
#define CC_SRCLKENA_MASK            (1U << 6)
#define CC_CXO32K_RM_EN_MD          (1U << 9)
#define CC_CXO32K_RM_EN_CONN        (1U << 10)
#define CC_CLKSQ0_SEL               (1U << 11)
#define CC_DISABLE_SODI             (1U << 13)
#define CC_DISABLE_DORM_PWR         (1U << 14)
#define CC_DISABLE_INFRA_PWR        (1U << 15)
#define CC_SRCLKEN0_EN              (1U << 16)

#define WAKE_SRC_TS                 (1U << 1)
#define WAKE_SRC_KP                 (1U << 2)
#define WAKE_SRC_WDT                (1U << 3)
#define WAKE_SRC_GPT                (1U << 4)
#define WAKE_SRC_EINT               (1U << 5)
#define WAKE_SRC_CONN_WDT           (1U << 6)
#define WAKE_SRC_CCIF_MD            (1U << 8)
#define WAKE_SRC_LOW_BAT            (1U << 9)
#define WAKE_SRC_CONN               (1U << 10)
#define WAKE_SRC_USB_CD             (1U << 14)
#define WAKE_SRC_USB_PDN            (1U << 16)
#define WAKE_SRC_DBGSYS             (1U << 18)
#define WAKE_SRC_UART0              (1U << 19)
#define WAKE_SRC_AFE                (1U << 20)
#define WAKE_SRC_THERM              (1U << 21)
#define WAKE_SRC_CIRQ               (1U << 22)
#define WAKE_SRC_SYSPWREQ           (1U << 24)
#define WAKE_SRC_MD_WDT             (1U << 25)
#define WAKE_SRC_CPU0_IRQ           (1U << 26)
#define WAKE_SRC_CPU1_IRQ           (1U << 27)
#define WAKE_SRC_CPU2_IRQ           (1U << 28)
#define WAKE_SRC_CPU3_IRQ           (1U << 29)

#define EVENT_VEC(event, resume, imme, pc)  \
    (((event) << 0) | ((resume) << 5) | ((imme) << 6) | ((pc) << 16))

#define spm_read(addr)              (*(volatile u32 *)(addr))
#define spm_write(addr, val)        mt65xx_reg_sync_writel(val, addr)

#endif
