include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo")
obj-y   +=  nt35590_hd720_dsi_cmd_auo.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_wvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_wvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_fwvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_fwvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_qhd")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_qhd.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"hx8394d_hd720_dsi_vdo_truly")
obj-y   +=  hx8394d_hd720_dsi_vdo_truly.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"hx8394_hd720_dsi_vdo_truly")
obj-y   +=  hx8394_hd720_dsi_vdo_truly.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"hx8389_qhd_dsi_vdo_truly")
obj-y   +=  hx8389_qhd_dsi_vdo_truly.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"hx8389b_qhd_dsi_vdo_tianma")
obj-y   +=  hx8389b_qhd_dsi_vdo_tianma.o
endif