###################################################################
# flag
###################################################################

MOD_SRC  = 
MOD_OBJ  = $(MTK_ROOT_OUT)/PRELOADER_OBJ/obj

###################################################################
# source files
# - add your file here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################################################################

MOD_SRC  := \
	addr_trans.c \
	blkdev.c \
	div0.c \
	download.c \
	eabi_uldivmod.s \
	eabi_idiv.s \
	eabi.s \
	handshake_uart.c \
	handshake_usb.c \
	main.c \
	part.c \
	print.c \
	stdlib.c \
	string.c \
	dram_buffer.c \
	cache-ops.s\
	mmu.c
###################################################################
# target
###################################################################

include $(COMMON_FILE_MK)
